# coding: utf-8

# flake8: noqa
"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# TYPE_CHECKING imports for IDE support while maintaining lazy loading
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    # Import all Model classes for IDE type checking and autocompletion
    from .agent_status_response import AgentStatusResponse
    from .api_key_create import ApiKeyCreate
    from .api_key_create_result_public import ApiKeyCreateResultPublic
    from .api_key_public_read import ApiKeyPublicRead
    from .applicable_limit_read import ApplicableLimitRead
    from .audit_action import AuditAction
    from .audit_log_page import AuditLogPage
    from .audit_log_read import AuditLogRead
    from .audit_result import AuditResult
    from .balance_read import BalanceRead
    from .chain_info import ChainInfo
    from .chain_metadata import ChainMetadata
    from .completion_condition import CompletionCondition
    from .completion_condition_type import CompletionConditionType
    from .contract_call_create import ContractCallCreate
    from .contract_call_submit_result import ContractCallSubmitResult
    from .delegation_spend_summary import DelegationSpendSummary
    from .delegation_usage_limit_summary import DelegationUsageLimitSummary
    from .drop_transaction_request import DropTransactionRequest
    from .eip1559_fee_request import EIP1559FeeRequest
    from .evm_legacy_fee_request import EVMLegacyFeeRequest
    from .error import Error
    from .estimate_contract_call_fee_request import EstimateContractCallFeeRequest
    from .estimate_transfer_fee_read import EstimateTransferFeeRead
    from .estimate_transfer_fee_request import EstimateTransferFeeRequest
    from .eth_call_request import EthCallRequest
    from .eth_call_result import EthCallResult
    from .execute_script_request import ExecuteScriptRequest
    from .execute_script_response import ExecuteScriptResponse
    from .external_transaction_operation_type import ExternalTransactionOperationType
    from .external_transaction_read import ExternalTransactionRead
    from .external_transaction_stage import ExternalTransactionStage
    from .faucet_deposit_request import FaucetDepositRequest
    from .faucet_deposit_result import FaucetDepositResult
    from .faucet_token_info import FaucetTokenInfo
    from .faucet_token_item import FaucetTokenItem
    from .fee_estimate_read import FeeEstimateRead
    from .fee_request import FeeRequest
    from .inline_policy_create import InlinePolicyCreate
    from .key_share_holder_group_status import KeyShareHolderGroupStatus
    from .key_share_holder_group_type import KeyShareHolderGroupType
    from .key_share_holder_type import KeyShareHolderType
    from .knowledge_search_type import KnowledgeSearchType
    from .langfuse_record import LangfuseRecord
    from .message_sign_create import MessageSignCreate
    from .message_sign_dest_type import MessageSignDestType
    from .message_sign_result import MessageSignResult
    from .mpp_challenge import MppChallenge
    from .mpp_session_action import MppSessionAction
    from .mpp_session_info import MppSessionInfo
    from .mpp_session_params import MppSessionParams
    from .node_status_read import NodeStatusRead
    from .pact_event_list_response import PactEventListResponse
    from .pact_event_read import PactEventRead
    from .pact_event_type import PactEventType
    from .pact_list_response import PactListResponse
    from .pact_public_read import PactPublicRead
    from .pact_spec_input import PactSpecInput
    from .pact_spec_output import PactSpecOutput
    from .pact_stats_language import PactStatsLanguage
    from .pact_status import PactStatus
    from .pact_submit_request import PactSubmitRequest
    from .pact_submit_response import PactSubmitResponse
    from .pact_summary import PactSummary
    from .pact_update_completion_conditions_request import PactUpdateCompletionConditionsRequest
    from .pact_update_policies_request import PactUpdatePoliciesRequest
    from .pagination_meta import PaginationMeta
    from .pair_token_status import PairTokenStatus
    from .payment_create import PaymentCreate
    from .payment_protocol import PaymentProtocol
    from .payment_result import PaymentResult
    from .pending_operation_action_result import PendingOperationActionResult
    from .pending_operation_list_response import PendingOperationListResponse
    from .pending_operation_read import PendingOperationRead
    from .pending_operation_status import PendingOperationStatus
    from .pending_operation_type import PendingOperationType
    from .policy_create import PolicyCreate
    from .policy_dry_run_request import PolicyDryRunRequest
    from .policy_dry_run_result import PolicyDryRunResult
    from .policy_read import PolicyRead
    from .policy_scope import PolicyScope
    from .policy_type import PolicyType
    from .policy_update import PolicyUpdate
    from .principal_create import PrincipalCreate
    from .principal_create_result import PrincipalCreateResult
    from .principal_read import PrincipalRead
    from .principal_type import PrincipalType
    from .principal_update import PrincipalUpdate
    from .provision_request import ProvisionRequest
    from .provision_response import ProvisionResponse
    from .recent_address_read import RecentAddressRead
    from .recipe_category_read import RecipeCategoryRead
    from .recipe_counter_result import RecipeCounterResult
    from .recipe_create import RecipeCreate
    from .recipe_create_result import RecipeCreateResult
    from .recipe_detail_read import RecipeDetailRead
    from .recipe_document import RecipeDocument
    from .recipe_library_sort_by import RecipeLibrarySortBy
    from .recipe_read import RecipeRead
    from .recipe_review_action import RecipeReviewAction
    from .recipe_review_request import RecipeReviewRequest
    from .recipe_search_response import RecipeSearchResponse
    from .recipe_search_source import RecipeSearchSource
    from .recipe_status import RecipeStatus
    from .recipe_submission_create import RecipeSubmissionCreate
    from .recipe_update import RecipeUpdate
    from .reject_pending_operation_request import RejectPendingOperationRequest
    from .sol_fee_request import SOLFeeRequest
    from .script_brief import ScriptBrief
    from .search_recipes_request import SearchRecipesRequest
    from .session_record import SessionRecord
    from .session_span import SessionSpan
    from .sol_address_lookup_table_account import SolAddressLookupTableAccount
    from .sol_instruction import SolInstruction
    from .sol_instruction_account import SolInstructionAccount
    from .speedup_transaction_request import SpeedupTransactionRequest
    from .standard_response_agent_status_response import StandardResponseAgentStatusResponse
    from .standard_response_api_key_create_result_public import (
        StandardResponseApiKeyCreateResultPublic,
    )
    from .standard_response_audit_log_page import StandardResponseAuditLogPage
    from .standard_response_chain_info import StandardResponseChainInfo
    from .standard_response_contract_call_submit_result import (
        StandardResponseContractCallSubmitResult,
    )
    from .standard_response_dict_str_bool import StandardResponseDictStrBool
    from .standard_response_dict_str_str import StandardResponseDictStrStr
    from .standard_response_estimate_transfer_fee_read import (
        StandardResponseEstimateTransferFeeRead,
    )
    from .standard_response_eth_call_result import StandardResponseEthCallResult
    from .standard_response_execute_script_response import StandardResponseExecuteScriptResponse
    from .standard_response_faucet_deposit_result import StandardResponseFaucetDepositResult
    from .standard_response_list_api_key_public_read import StandardResponseListApiKeyPublicRead
    from .standard_response_list_balance_read import StandardResponseListBalanceRead
    from .standard_response_list_faucet_token_item import StandardResponseListFaucetTokenItem
    from .standard_response_list_policy_read import StandardResponseListPolicyRead
    from .standard_response_list_principal_read import StandardResponseListPrincipalRead
    from .standard_response_list_recent_address_read import StandardResponseListRecentAddressRead
    from .standard_response_list_recipe_category_read import StandardResponseListRecipeCategoryRead
    from .standard_response_list_recipe_read import StandardResponseListRecipeRead
    from .standard_response_list_script_brief import StandardResponseListScriptBrief
    from .standard_response_list_token_candidate import StandardResponseListTokenCandidate
    from .standard_response_list_user_transaction_read import (
        StandardResponseListUserTransactionRead,
    )
    from .standard_response_list_wallet_address_read import StandardResponseListWalletAddressRead
    from .standard_response_list_wallet_read import StandardResponseListWalletRead
    from .standard_response_message_sign_result import StandardResponseMessageSignResult
    from .standard_response_node_status_read import StandardResponseNodeStatusRead
    from .standard_response_pact_event_list_response import StandardResponsePactEventListResponse
    from .standard_response_pact_list_response import StandardResponsePactListResponse
    from .standard_response_pact_public_read import StandardResponsePactPublicRead
    from .standard_response_pact_submit_response import StandardResponsePactSubmitResponse
    from .standard_response_payment_result import StandardResponsePaymentResult
    from .standard_response_pending_operation_action_result import (
        StandardResponsePendingOperationActionResult,
    )
    from .standard_response_pending_operation_list_response import (
        StandardResponsePendingOperationListResponse,
    )
    from .standard_response_pending_operation_read import StandardResponsePendingOperationRead
    from .standard_response_policy_dry_run_result import StandardResponsePolicyDryRunResult
    from .standard_response_policy_read import StandardResponsePolicyRead
    from .standard_response_principal_create_result import StandardResponsePrincipalCreateResult
    from .standard_response_principal_read import StandardResponsePrincipalRead
    from .standard_response_provision_response import StandardResponseProvisionResponse
    from .standard_response_recipe_counter_result import StandardResponseRecipeCounterResult
    from .standard_response_recipe_create_result import StandardResponseRecipeCreateResult
    from .standard_response_recipe_detail_read import StandardResponseRecipeDetailRead
    from .standard_response_recipe_document import StandardResponseRecipeDocument
    from .standard_response_recipe_search_response import StandardResponseRecipeSearchResponse
    from .standard_response_suggestion_response import StandardResponseSuggestionResponse
    from .standard_response_telemetry_config_response import StandardResponseTelemetryConfigResponse
    from .standard_response_transaction_rbf_result import StandardResponseTransactionRbfResult
    from .standard_response_transfer_submit_result import StandardResponseTransferSubmitResult
    from .standard_response_user_transaction_read import StandardResponseUserTransactionRead
    from .standard_response_waas_paginated_response_chain_metadata import (
        StandardResponseWaasPaginatedResponseChainMetadata,
    )
    from .standard_response_waas_paginated_response_token_metadata import (
        StandardResponseWaasPaginatedResponseTokenMetadata,
    )
    from .standard_response_wallet_address_read import StandardResponseWalletAddressRead
    from .standard_response_wallet_detail_read import StandardResponseWalletDetailRead
    from .standard_response_wallet_pact_history_read import StandardResponseWalletPactHistoryRead
    from .standard_response_wallet_pact_stats_read import StandardResponseWalletPactStatsRead
    from .standard_response_wallet_pair_info_read import StandardResponseWalletPairInfoRead
    from .standard_response_wallet_pair_initiate_read import StandardResponseWalletPairInitiateRead
    from .standard_response_wallet_pair_read import StandardResponseWalletPairRead
    from .standard_response_wallet_read import StandardResponseWalletRead
    from .standard_response_wallet_reshare_response import StandardResponseWalletReshareResponse
    from .standard_response_wallet_tss_callback_response import (
        StandardResponseWalletTssCallbackResponse,
    )
    from .standard_response_webhook_process_result import StandardResponseWebhookProcessResult
    from .suggestion_key import SuggestionKey
    from .suggestion_response import SuggestionResponse
    from .telemetry_config_response import TelemetryConfigResponse
    from .tier_evaluation_read import TierEvaluationRead
    from .token_candidate import TokenCandidate
    from .token_metadata import TokenMetadata
    from .transaction_provider import TransactionProvider
    from .transaction_rbf_result import TransactionRbfResult
    from .transfer_create import TransferCreate
    from .transfer_submit_result import TransferSubmitResult
    from .ucw_share_public_data_callback import UcwSharePublicDataCallback
    from .ucw_tss_key_share_group_callback import UcwTssKeyShareGroupCallback
    from .user_transaction_data import UserTransactionData
    from .user_transaction_operation_type import UserTransactionOperationType
    from .user_transaction_read import UserTransactionRead
    from .user_transaction_request_type import UserTransactionRequestType
    from .validation_error import ValidationError
    from .validation_error_loc_inner import ValidationErrorLocInner
    from .vault_group_type import VaultGroupType
    from .waas_paginated_response_chain_metadata import WaasPaginatedResponseChainMetadata
    from .waas_paginated_response_token_metadata import WaasPaginatedResponseTokenMetadata
    from .waas_pagination import WaasPagination
    from .wallet_address_create import WalletAddressCreate
    from .wallet_address_read import WalletAddressRead
    from .wallet_create import WalletCreate
    from .wallet_detail_read import WalletDetailRead
    from .wallet_group_node_read import WalletGroupNodeRead
    from .wallet_group_read import WalletGroupRead
    from .wallet_pact_currency import WalletPactCurrency
    from .wallet_pact_history_bucket_pact_read import WalletPactHistoryBucketPactRead
    from .wallet_pact_history_bucket_read import WalletPactHistoryBucketRead
    from .wallet_pact_history_metric import WalletPactHistoryMetric
    from .wallet_pact_history_range import WalletPactHistoryRange
    from .wallet_pact_history_read import WalletPactHistoryRead
    from .wallet_pact_history_summary_read import WalletPactHistorySummaryRead
    from .wallet_pact_stats_read import WalletPactStatsRead
    from .wallet_pair_agent_info import WalletPairAgentInfo
    from .wallet_pair_confirm import WalletPairConfirm
    from .wallet_pair_info_read import WalletPairInfoRead
    from .wallet_pair_initiate import WalletPairInitiate
    from .wallet_pair_initiate_read import WalletPairInitiateRead
    from .wallet_pair_read import WalletPairRead
    from .wallet_pair_status import WalletPairStatus
    from .wallet_pair_wallet_info import WalletPairWalletInfo
    from .wallet_read import WalletRead
    from .wallet_reshare_request import WalletReshareRequest
    from .wallet_reshare_response import WalletReshareResponse
    from .wallet_status import WalletStatus
    from .wallet_tss_callback_request import WalletTssCallbackRequest
    from .wallet_tss_callback_response import WalletTssCallbackResponse
    from .wallet_type import WalletType
    from .wallet_update import WalletUpdate
    from .webhook_process_result import WebhookProcessResult
    from .wrapped_validation_error import WrappedValidationError


# Model classes mapping for lazy import
_MODEL_CLASSES = {
    "AgentStatusResponse": "agent_status_response",
    "ApiKeyCreate": "api_key_create",
    "ApiKeyCreateResultPublic": "api_key_create_result_public",
    "ApiKeyPublicRead": "api_key_public_read",
    "ApplicableLimitRead": "applicable_limit_read",
    "AuditAction": "audit_action",
    "AuditLogPage": "audit_log_page",
    "AuditLogRead": "audit_log_read",
    "AuditResult": "audit_result",
    "BalanceRead": "balance_read",
    "ChainInfo": "chain_info",
    "ChainMetadata": "chain_metadata",
    "CompletionCondition": "completion_condition",
    "CompletionConditionType": "completion_condition_type",
    "ContractCallCreate": "contract_call_create",
    "ContractCallSubmitResult": "contract_call_submit_result",
    "DelegationSpendSummary": "delegation_spend_summary",
    "DelegationUsageLimitSummary": "delegation_usage_limit_summary",
    "DropTransactionRequest": "drop_transaction_request",
    "EIP1559FeeRequest": "eip1559_fee_request",
    "EVMLegacyFeeRequest": "evm_legacy_fee_request",
    "Error": "error",
    "EstimateContractCallFeeRequest": "estimate_contract_call_fee_request",
    "EstimateTransferFeeRead": "estimate_transfer_fee_read",
    "EstimateTransferFeeRequest": "estimate_transfer_fee_request",
    "EthCallRequest": "eth_call_request",
    "EthCallResult": "eth_call_result",
    "ExecuteScriptRequest": "execute_script_request",
    "ExecuteScriptResponse": "execute_script_response",
    "ExternalTransactionOperationType": "external_transaction_operation_type",
    "ExternalTransactionRead": "external_transaction_read",
    "ExternalTransactionStage": "external_transaction_stage",
    "FaucetDepositRequest": "faucet_deposit_request",
    "FaucetDepositResult": "faucet_deposit_result",
    "FaucetTokenInfo": "faucet_token_info",
    "FaucetTokenItem": "faucet_token_item",
    "FeeEstimateRead": "fee_estimate_read",
    "FeeRequest": "fee_request",
    "InlinePolicyCreate": "inline_policy_create",
    "KeyShareHolderGroupStatus": "key_share_holder_group_status",
    "KeyShareHolderGroupType": "key_share_holder_group_type",
    "KeyShareHolderType": "key_share_holder_type",
    "KnowledgeSearchType": "knowledge_search_type",
    "LangfuseRecord": "langfuse_record",
    "MessageSignCreate": "message_sign_create",
    "MessageSignDestType": "message_sign_dest_type",
    "MessageSignResult": "message_sign_result",
    "MppChallenge": "mpp_challenge",
    "MppSessionAction": "mpp_session_action",
    "MppSessionInfo": "mpp_session_info",
    "MppSessionParams": "mpp_session_params",
    "NodeStatusRead": "node_status_read",
    "PactEventListResponse": "pact_event_list_response",
    "PactEventRead": "pact_event_read",
    "PactEventType": "pact_event_type",
    "PactListResponse": "pact_list_response",
    "PactPublicRead": "pact_public_read",
    "PactSpecInput": "pact_spec_input",
    "PactSpecOutput": "pact_spec_output",
    "PactStatsLanguage": "pact_stats_language",
    "PactStatus": "pact_status",
    "PactSubmitRequest": "pact_submit_request",
    "PactSubmitResponse": "pact_submit_response",
    "PactSummary": "pact_summary",
    "PactUpdateCompletionConditionsRequest": "pact_update_completion_conditions_request",
    "PactUpdatePoliciesRequest": "pact_update_policies_request",
    "PaginationMeta": "pagination_meta",
    "PairTokenStatus": "pair_token_status",
    "PaymentCreate": "payment_create",
    "PaymentProtocol": "payment_protocol",
    "PaymentResult": "payment_result",
    "PendingOperationActionResult": "pending_operation_action_result",
    "PendingOperationListResponse": "pending_operation_list_response",
    "PendingOperationRead": "pending_operation_read",
    "PendingOperationStatus": "pending_operation_status",
    "PendingOperationType": "pending_operation_type",
    "PolicyCreate": "policy_create",
    "PolicyDryRunRequest": "policy_dry_run_request",
    "PolicyDryRunResult": "policy_dry_run_result",
    "PolicyRead": "policy_read",
    "PolicyScope": "policy_scope",
    "PolicyType": "policy_type",
    "PolicyUpdate": "policy_update",
    "PrincipalCreate": "principal_create",
    "PrincipalCreateResult": "principal_create_result",
    "PrincipalRead": "principal_read",
    "PrincipalType": "principal_type",
    "PrincipalUpdate": "principal_update",
    "ProvisionRequest": "provision_request",
    "ProvisionResponse": "provision_response",
    "RecentAddressRead": "recent_address_read",
    "RecipeCategoryRead": "recipe_category_read",
    "RecipeCounterResult": "recipe_counter_result",
    "RecipeCreate": "recipe_create",
    "RecipeCreateResult": "recipe_create_result",
    "RecipeDetailRead": "recipe_detail_read",
    "RecipeDocument": "recipe_document",
    "RecipeLibrarySortBy": "recipe_library_sort_by",
    "RecipeRead": "recipe_read",
    "RecipeReviewAction": "recipe_review_action",
    "RecipeReviewRequest": "recipe_review_request",
    "RecipeSearchResponse": "recipe_search_response",
    "RecipeSearchSource": "recipe_search_source",
    "RecipeStatus": "recipe_status",
    "RecipeSubmissionCreate": "recipe_submission_create",
    "RecipeUpdate": "recipe_update",
    "RejectPendingOperationRequest": "reject_pending_operation_request",
    "SOLFeeRequest": "sol_fee_request",
    "ScriptBrief": "script_brief",
    "SearchRecipesRequest": "search_recipes_request",
    "SessionRecord": "session_record",
    "SessionSpan": "session_span",
    "SolAddressLookupTableAccount": "sol_address_lookup_table_account",
    "SolInstruction": "sol_instruction",
    "SolInstructionAccount": "sol_instruction_account",
    "SpeedupTransactionRequest": "speedup_transaction_request",
    "StandardResponseAgentStatusResponse": "standard_response_agent_status_response",
    "StandardResponseApiKeyCreateResultPublic": "standard_response_api_key_create_result_public",
    "StandardResponseAuditLogPage": "standard_response_audit_log_page",
    "StandardResponseChainInfo": "standard_response_chain_info",
    "StandardResponseContractCallSubmitResult": "standard_response_contract_call_submit_result",
    "StandardResponseDictStrBool": "standard_response_dict_str_bool",
    "StandardResponseDictStrStr": "standard_response_dict_str_str",
    "StandardResponseEstimateTransferFeeRead": "standard_response_estimate_transfer_fee_read",
    "StandardResponseEthCallResult": "standard_response_eth_call_result",
    "StandardResponseExecuteScriptResponse": "standard_response_execute_script_response",
    "StandardResponseFaucetDepositResult": "standard_response_faucet_deposit_result",
    "StandardResponseListApiKeyPublicRead": "standard_response_list_api_key_public_read",
    "StandardResponseListBalanceRead": "standard_response_list_balance_read",
    "StandardResponseListFaucetTokenItem": "standard_response_list_faucet_token_item",
    "StandardResponseListPolicyRead": "standard_response_list_policy_read",
    "StandardResponseListPrincipalRead": "standard_response_list_principal_read",
    "StandardResponseListRecentAddressRead": "standard_response_list_recent_address_read",
    "StandardResponseListRecipeCategoryRead": "standard_response_list_recipe_category_read",
    "StandardResponseListRecipeRead": "standard_response_list_recipe_read",
    "StandardResponseListScriptBrief": "standard_response_list_script_brief",
    "StandardResponseListTokenCandidate": "standard_response_list_token_candidate",
    "StandardResponseListUserTransactionRead": "standard_response_list_user_transaction_read",
    "StandardResponseListWalletAddressRead": "standard_response_list_wallet_address_read",
    "StandardResponseListWalletRead": "standard_response_list_wallet_read",
    "StandardResponseMessageSignResult": "standard_response_message_sign_result",
    "StandardResponseNodeStatusRead": "standard_response_node_status_read",
    "StandardResponsePactEventListResponse": "standard_response_pact_event_list_response",
    "StandardResponsePactListResponse": "standard_response_pact_list_response",
    "StandardResponsePactPublicRead": "standard_response_pact_public_read",
    "StandardResponsePactSubmitResponse": "standard_response_pact_submit_response",
    "StandardResponsePaymentResult": "standard_response_payment_result",
    "StandardResponsePendingOperationActionResult": "standard_response_pending_operation_action_result",
    "StandardResponsePendingOperationListResponse": "standard_response_pending_operation_list_response",
    "StandardResponsePendingOperationRead": "standard_response_pending_operation_read",
    "StandardResponsePolicyDryRunResult": "standard_response_policy_dry_run_result",
    "StandardResponsePolicyRead": "standard_response_policy_read",
    "StandardResponsePrincipalCreateResult": "standard_response_principal_create_result",
    "StandardResponsePrincipalRead": "standard_response_principal_read",
    "StandardResponseProvisionResponse": "standard_response_provision_response",
    "StandardResponseRecipeCounterResult": "standard_response_recipe_counter_result",
    "StandardResponseRecipeCreateResult": "standard_response_recipe_create_result",
    "StandardResponseRecipeDetailRead": "standard_response_recipe_detail_read",
    "StandardResponseRecipeDocument": "standard_response_recipe_document",
    "StandardResponseRecipeSearchResponse": "standard_response_recipe_search_response",
    "StandardResponseSuggestionResponse": "standard_response_suggestion_response",
    "StandardResponseTelemetryConfigResponse": "standard_response_telemetry_config_response",
    "StandardResponseTransactionRbfResult": "standard_response_transaction_rbf_result",
    "StandardResponseTransferSubmitResult": "standard_response_transfer_submit_result",
    "StandardResponseUserTransactionRead": "standard_response_user_transaction_read",
    "StandardResponseWaasPaginatedResponseChainMetadata": "standard_response_waas_paginated_response_chain_metadata",
    "StandardResponseWaasPaginatedResponseTokenMetadata": "standard_response_waas_paginated_response_token_metadata",
    "StandardResponseWalletAddressRead": "standard_response_wallet_address_read",
    "StandardResponseWalletDetailRead": "standard_response_wallet_detail_read",
    "StandardResponseWalletPactHistoryRead": "standard_response_wallet_pact_history_read",
    "StandardResponseWalletPactStatsRead": "standard_response_wallet_pact_stats_read",
    "StandardResponseWalletPairInfoRead": "standard_response_wallet_pair_info_read",
    "StandardResponseWalletPairInitiateRead": "standard_response_wallet_pair_initiate_read",
    "StandardResponseWalletPairRead": "standard_response_wallet_pair_read",
    "StandardResponseWalletRead": "standard_response_wallet_read",
    "StandardResponseWalletReshareResponse": "standard_response_wallet_reshare_response",
    "StandardResponseWalletTssCallbackResponse": "standard_response_wallet_tss_callback_response",
    "StandardResponseWebhookProcessResult": "standard_response_webhook_process_result",
    "SuggestionKey": "suggestion_key",
    "SuggestionResponse": "suggestion_response",
    "TelemetryConfigResponse": "telemetry_config_response",
    "TierEvaluationRead": "tier_evaluation_read",
    "TokenCandidate": "token_candidate",
    "TokenMetadata": "token_metadata",
    "TransactionProvider": "transaction_provider",
    "TransactionRbfResult": "transaction_rbf_result",
    "TransferCreate": "transfer_create",
    "TransferSubmitResult": "transfer_submit_result",
    "UcwSharePublicDataCallback": "ucw_share_public_data_callback",
    "UcwTssKeyShareGroupCallback": "ucw_tss_key_share_group_callback",
    "UserTransactionData": "user_transaction_data",
    "UserTransactionOperationType": "user_transaction_operation_type",
    "UserTransactionRead": "user_transaction_read",
    "UserTransactionRequestType": "user_transaction_request_type",
    "ValidationError": "validation_error",
    "ValidationErrorLocInner": "validation_error_loc_inner",
    "VaultGroupType": "vault_group_type",
    "WaasPaginatedResponseChainMetadata": "waas_paginated_response_chain_metadata",
    "WaasPaginatedResponseTokenMetadata": "waas_paginated_response_token_metadata",
    "WaasPagination": "waas_pagination",
    "WalletAddressCreate": "wallet_address_create",
    "WalletAddressRead": "wallet_address_read",
    "WalletCreate": "wallet_create",
    "WalletDetailRead": "wallet_detail_read",
    "WalletGroupNodeRead": "wallet_group_node_read",
    "WalletGroupRead": "wallet_group_read",
    "WalletPactCurrency": "wallet_pact_currency",
    "WalletPactHistoryBucketPactRead": "wallet_pact_history_bucket_pact_read",
    "WalletPactHistoryBucketRead": "wallet_pact_history_bucket_read",
    "WalletPactHistoryMetric": "wallet_pact_history_metric",
    "WalletPactHistoryRange": "wallet_pact_history_range",
    "WalletPactHistoryRead": "wallet_pact_history_read",
    "WalletPactHistorySummaryRead": "wallet_pact_history_summary_read",
    "WalletPactStatsRead": "wallet_pact_stats_read",
    "WalletPairAgentInfo": "wallet_pair_agent_info",
    "WalletPairConfirm": "wallet_pair_confirm",
    "WalletPairInfoRead": "wallet_pair_info_read",
    "WalletPairInitiate": "wallet_pair_initiate",
    "WalletPairInitiateRead": "wallet_pair_initiate_read",
    "WalletPairRead": "wallet_pair_read",
    "WalletPairStatus": "wallet_pair_status",
    "WalletPairWalletInfo": "wallet_pair_wallet_info",
    "WalletRead": "wallet_read",
    "WalletReshareRequest": "wallet_reshare_request",
    "WalletReshareResponse": "wallet_reshare_response",
    "WalletStatus": "wallet_status",
    "WalletTssCallbackRequest": "wallet_tss_callback_request",
    "WalletTssCallbackResponse": "wallet_tss_callback_response",
    "WalletType": "wallet_type",
    "WalletUpdate": "wallet_update",
    "WebhookProcessResult": "webhook_process_result",
    "WrappedValidationError": "wrapped_validation_error",
}


def __getattr__(name):
    """Lazy import for Model classes."""
    if name in _MODEL_CLASSES:
        module_name = f"cobo_agentic_wallet_api.models.{_MODEL_CLASSES[name]}"
        module = __import__(module_name, fromlist=[name])
        attr = getattr(module, name)
        globals()[name] = attr
        return attr
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")


def __dir__():
    """Support for autocompletion."""
    return list(globals().keys()) + list(_MODEL_CLASSES.keys())
