# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.2.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Set
from typing_extensions import Self


class ApiKeyCreate(BaseModel):
    """
    Request payload for creating an API key.
    """  # noqa: E501

    principal_id: Optional[StrictStr] = Field(
        default=None,
        description="The ID of the principal to create the API key for. Required when using service credential authentication; ignored when using principal API key authentication.",
    )
    name: Annotated[str, Field(strict=True, max_length=255)] = Field(
        description="The display name for this API key. Max 255 characters."
    )
    scopes: Optional[List[StrictStr]] = Field(
        default=None,
        description='The access scopes for this key. Use `["*"]` for full access, or restrict with `resource:action` format (for example, `["wallet:read", "wallet:write"]`). Possible actions: `read`, `write`, `status`.',
    )
    expires_at: Optional[datetime] = Field(
        default=None,
        description="The expiry timestamp for this key, in ISO 8601 format. If omitted, the key does not expire.",
    )
    __properties: ClassVar[List[str]] = ["principal_id", "name", "scopes", "expires_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiKeyCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiKeyCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "principal_id": obj.get("principal_id"),
                "name": obj.get("name"),
                "scopes": obj.get("scopes"),
                "expires_at": obj.get("expires_at"),
            }
        )
        return _obj
