# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_agentic_wallet_api.models.approval_status import ApprovalStatus
from cobo_agentic_wallet_api.models.approval_subject_type import ApprovalSubjectType
from cobo_agentic_wallet_api.models.request import Request
from cobo_agentic_wallet_api.models.response import Response
from typing import Set
from typing_extensions import Self


class ApprovalRead(BaseModel):
    """
    Approval read schema.
    """  # noqa: E501

    id: StrictStr
    subject_type: ApprovalSubjectType
    subject_id: StrictStr
    request: Optional[Request] = None
    response: Optional[Response] = None
    initiator_id: StrictStr
    owner_id: StrictStr
    status: ApprovalStatus
    error: Optional[str] = None
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = [
        "id",
        "subject_type",
        "subject_id",
        "request",
        "response",
        "initiator_id",
        "owner_id",
        "status",
        "error",
        "created_at",
        "updated_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApprovalRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of request
        if self.request:
            _dict["request"] = self.request.to_dict()
        # override the default output from pydantic by calling `to_dict()` of response
        if self.response:
            _dict["response"] = self.response.to_dict()
        # set to None if request (nullable) is None
        # and model_fields_set contains the field
        if self.request is None and "request" in self.model_fields_set:
            _dict["request"] = None

        # set to None if response (nullable) is None
        # and model_fields_set contains the field
        if self.response is None and "response" in self.model_fields_set:
            _dict["response"] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict["error"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApprovalRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "subject_type": obj.get("subject_type"),
                "subject_id": obj.get("subject_id"),
                "request": Request.from_dict(obj["request"])
                if obj.get("request") is not None
                else None,
                "response": Response.from_dict(obj["response"])
                if obj.get("response") is not None
                else None,
                "initiator_id": obj.get("initiator_id"),
                "owner_id": obj.get("owner_id"),
                "status": obj.get("status"),
                "error": obj.get("error"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
            }
        )
        return _obj
