# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AuditAction(str, Enum):
    """
    Audit action.
    """

    """
    allowed enum values
    """
    UNKNOWN = "unknown"
    AUTHZ_DOT_CHECK = "authz.check"
    AUTHZ_DOT_OWNER_CHECK = "authz.owner_check"
    DELEGATION_DOT_FREEZE = "delegation.freeze"
    DELEGATION_DOT_UNFREEZE = "delegation.unfreeze"
    APPROVAL_DOT_APPROVED = "approval.approved"
    APPROVAL_DOT_REJECTED = "approval.rejected"
    SIGN_APPROVAL_DOT_CREATED = "sign_approval.created"
    SIGN_APPROVAL_DOT_APPROVED = "sign_approval.approved"
    SIGN_APPROVAL_DOT_REJECTED = "sign_approval.rejected"
    WALLET_DOT_READ = "wallet.read"
    WALLET_DOT_UPDATE = "wallet.update"
    WALLET_DOT_ARCHIVE = "wallet.archive"
    WALLET_DOT_ADDRESS_DOT_CREATE = "wallet.address.create"
    WALLET_DOT_ADDRESS_DOT_LIST = "wallet.address.list"
    WALLET_DOT_BALANCES = "wallet.balances"
    WALLET_DOT_NODE_STATUS = "wallet.node_status"
    TRANSFER_DOT_INITIATE = "transfer.initiate"
    TRANSFER_DOT_ESTIMATE_FEE = "transfer.estimate_fee"
    TRANSFER_DOT_ALLOWED = "transfer.allowed"
    TRANSFER_DOT_DENIED = "transfer.denied"
    TRANSFER_DOT_APPROVAL_REQUIRED = "transfer.approval_required"
    TRANSFER_DOT_APPROVAL_DOT_APPROVED = "transfer.approval.approved"
    TRANSFER_DOT_APPROVAL_DOT_REJECTED = "transfer.approval.rejected"
    TRANSFER_DOT_APPROVAL_DOT_EXPIRED = "transfer.approval.expired"
    TRANSFER_DOT_APPROVAL_DOT_EXECUTED = "transfer.approval.executed"
    TRANSFER_DOT_APPROVAL_DOT_EXECUTION_FAILED = "transfer.approval.execution_failed"
    CONTRACT_CALL_DOT_INITIATE = "contract_call.initiate"
    CONTRACT_CALL_DOT_ESTIMATE_FEE = "contract_call.estimate_fee"
    CONTRACT_CALL_DOT_ALLOWED = "contract_call.allowed"
    CONTRACT_CALL_DOT_DENIED = "contract_call.denied"
    CONTRACT_CALL_DOT_APPROVAL_REQUIRED = "contract_call.approval_required"
    CONTRACT_CALL_DOT_APPROVAL_DOT_APPROVED = "contract_call.approval.approved"
    CONTRACT_CALL_DOT_APPROVAL_DOT_REJECTED = "contract_call.approval.rejected"
    CONTRACT_CALL_DOT_APPROVAL_DOT_EXPIRED = "contract_call.approval.expired"
    CONTRACT_CALL_DOT_APPROVAL_DOT_EXECUTED = "contract_call.approval.executed"
    CONTRACT_CALL_DOT_APPROVAL_DOT_EXECUTION_FAILED = "contract_call.approval.execution_failed"
    MESSAGE_SIGN_DOT_INITIATE = "message_sign.initiate"
    MESSAGE_SIGN_DOT_ALLOWED = "message_sign.allowed"
    MESSAGE_SIGN_DOT_DENIED = "message_sign.denied"
    MESSAGE_SIGN_DOT_APPROVAL_REQUIRED = "message_sign.approval_required"
    MESSAGE_SIGN_DOT_APPROVAL_DOT_APPROVED = "message_sign.approval.approved"
    MESSAGE_SIGN_DOT_APPROVAL_DOT_REJECTED = "message_sign.approval.rejected"
    MESSAGE_SIGN_DOT_APPROVAL_DOT_EXPIRED = "message_sign.approval.expired"
    MESSAGE_SIGN_DOT_APPROVAL_DOT_EXECUTED = "message_sign.approval.executed"
    MESSAGE_SIGN_DOT_APPROVAL_DOT_EXECUTION_FAILED = "message_sign.approval.execution_failed"
    TRANSACTION_DOT_LIST = "transaction.list"
    TRANSACTION_DOT_LIST_RECENT_ADDRESSES = "transaction.list_recent_addresses"
    TRANSACTION_DOT_READ = "transaction.read"
    TRANSACTION_DOT_DROP = "transaction.drop"
    TRANSACTION_DOT_SPEEDUP = "transaction.speedup"
    USER_TRANSACTION_DOT_LIST = "user_transaction.list"
    USER_TRANSACTION_DOT_READ = "user_transaction.read"
    POLICY_DOT_CREATE = "policy.create"
    POLICY_DOT_LIST = "policy.list"
    POLICY_DOT_GET = "policy.get"
    POLICY_DOT_UPDATE = "policy.update"
    POLICY_DOT_DEACTIVATE = "policy.deactivate"
    POLICY_DOT_DRY_RUN = "policy.dry_run"
    FAUCET_DOT_DEPOSIT = "faucet.deposit"

    _UNKNOWN_FALLBACK = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AuditAction from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls._UNKNOWN_FALLBACK

    @classmethod
    def to_choices(cls) -> list[tuple[str, str]]:
        return [(member.value, member.name) for member in cls if member != cls._UNKNOWN_FALLBACK]
