# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.2.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class ChainInfo(BaseModel):
    """
    Single chain info from get_chains_by_chain_coins.  All optional fields use ``str | None`` because the upstream Blockchain API may return ``null`` for any non-essential attribute.
    """  # noqa: E501

    unique_chain_id: StrictStr
    name: StrictStr
    chain_coin: StrictStr
    icon_url: Optional[StrictStr] = None
    confirming_threshold: Optional[StrictInt] = 0
    chain_type: Optional[StrictStr] = Field(
        default="",
        description="The address standard shared across chains — chains with the same chain_type share one wallet address. E.g. ETH, BASE, ARB, OP, BSC, MATIC, AVAXC, and SETH are all chain_type: ETH, so they all use the same 0x... address.",
    )
    explorer_tx_url: Optional[StrictStr] = ""
    explorer_address_url: Optional[StrictStr] = ""
    supported_fee_models: Optional[StrictStr] = ""
    supported_address_encodings: Optional[StrictStr] = ""
    supported_address_encodings_by_ksr: Optional[StrictStr] = ""
    enable_smart_contract_op: Optional[StrictBool] = False
    is_nonce_mandatory: Optional[StrictBool] = False
    is_case_sensitive: Optional[StrictBool] = False
    is_testnet: Optional[StrictBool] = False
    use_memo_to_deposit: Optional[StrictBool] = False
    use_memo_to_withdraw: Optional[StrictBool] = False
    coinbase_maturity: Optional[StrictInt] = 0
    input_utxo_limit: Optional[StrictInt] = 0
    caip2_chain_id: Optional[StrictStr] = ""
    __properties: ClassVar[List[str]] = [
        "unique_chain_id",
        "name",
        "chain_coin",
        "icon_url",
        "confirming_threshold",
        "chain_type",
        "explorer_tx_url",
        "explorer_address_url",
        "supported_fee_models",
        "supported_address_encodings",
        "supported_address_encodings_by_ksr",
        "enable_smart_contract_op",
        "is_nonce_mandatory",
        "is_case_sensitive",
        "is_testnet",
        "use_memo_to_deposit",
        "use_memo_to_withdraw",
        "coinbase_maturity",
        "input_utxo_limit",
        "caip2_chain_id",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChainInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChainInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "unique_chain_id": obj.get("unique_chain_id"),
                "name": obj.get("name"),
                "chain_coin": obj.get("chain_coin"),
                "icon_url": obj.get("icon_url"),
                "confirming_threshold": obj.get("confirming_threshold")
                if obj.get("confirming_threshold") is not None
                else 0,
                "chain_type": obj.get("chain_type") if obj.get("chain_type") is not None else "",
                "explorer_tx_url": obj.get("explorer_tx_url")
                if obj.get("explorer_tx_url") is not None
                else "",
                "explorer_address_url": obj.get("explorer_address_url")
                if obj.get("explorer_address_url") is not None
                else "",
                "supported_fee_models": obj.get("supported_fee_models")
                if obj.get("supported_fee_models") is not None
                else "",
                "supported_address_encodings": obj.get("supported_address_encodings")
                if obj.get("supported_address_encodings") is not None
                else "",
                "supported_address_encodings_by_ksr": obj.get("supported_address_encodings_by_ksr")
                if obj.get("supported_address_encodings_by_ksr") is not None
                else "",
                "enable_smart_contract_op": obj.get("enable_smart_contract_op")
                if obj.get("enable_smart_contract_op") is not None
                else False,
                "is_nonce_mandatory": obj.get("is_nonce_mandatory")
                if obj.get("is_nonce_mandatory") is not None
                else False,
                "is_case_sensitive": obj.get("is_case_sensitive")
                if obj.get("is_case_sensitive") is not None
                else False,
                "is_testnet": obj.get("is_testnet") if obj.get("is_testnet") is not None else False,
                "use_memo_to_deposit": obj.get("use_memo_to_deposit")
                if obj.get("use_memo_to_deposit") is not None
                else False,
                "use_memo_to_withdraw": obj.get("use_memo_to_withdraw")
                if obj.get("use_memo_to_withdraw") is not None
                else False,
                "coinbase_maturity": obj.get("coinbase_maturity")
                if obj.get("coinbase_maturity") is not None
                else 0,
                "input_utxo_limit": obj.get("input_utxo_limit")
                if obj.get("input_utxo_limit") is not None
                else 0,
                "caip2_chain_id": obj.get("caip2_chain_id")
                if obj.get("caip2_chain_id") is not None
                else "",
            }
        )
        return _obj
