# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CompletionConditionType(str, Enum):
    """
    Supported pact completion condition types.
    """

    """
    allowed enum values
    """
    TIME_ELAPSED = "time_elapsed"
    TX_COUNT = "tx_count"
    AMOUNT_SPENT = "amount_spent"
    AMOUNT_SPENT_USD = "amount_spent_usd"
    MANUAL = "manual"

    _UNKNOWN_FALLBACK = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CompletionConditionType from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls._UNKNOWN_FALLBACK

    @classmethod
    def to_choices(cls) -> list[tuple[str, str]]:
        return [(member.value, member.name) for member in cls if member != cls._UNKNOWN_FALLBACK]
