# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cobo_agentic_wallet_api.models.fee_request import FeeRequest
from cobo_agentic_wallet_api.models.sol_address_lookup_table_account import (
    SolAddressLookupTableAccount,
)
from cobo_agentic_wallet_api.models.sol_instruction import SolInstruction
from typing import Set
from typing_extensions import Self


class ContractCallCreate(BaseModel):
    """
    Request payload for contract call (EVM or Solana).
    """  # noqa: E501

    chain_id: Annotated[str, Field(min_length=1, strict=True, max_length=100)] = Field(
        description="The Cobo chain ID for this contract call (for example, `SETH`, `BASE_ETH`, `SOL`). Use the List supported chains operation to retrieve all supported chain IDs."
    )
    contract_addr: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None, description="The EVM contract address to call. Required for EVM chains."
    )
    value: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100)]] = Field(
        default="0",
        description="The ETH value to send with the call, in whole token units (not wei), as a decimal string. Defaults to `0`.",
    )
    calldata: Optional[Annotated[str, Field(strict=True, max_length=8192)]] = Field(
        default=None,
        description="The ABI-encoded calldata for the EVM function call, as a hex string.",
    )
    instructions: Optional[List[SolInstruction]] = Field(
        default=None,
        description="The Solana instructions for this call. Required for Solana chains.",
    )
    address_lookup_table_accounts: Optional[List[SolAddressLookupTableAccount]] = Field(
        default=None, description="Optional Solana address lookup table accounts for this call."
    )
    request_id: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None,
        description="A client-supplied identifier for idempotency. If a contract call with the same `request_id` already exists for the same principal, the existing record is returned.",
    )
    fee: Optional[FeeRequest] = None
    src_addr: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None,
        description="The source address to call from. If omitted, the server auto-selects the wallet address on this chain with the highest available native token balance for this chain (explicit `src_addr` always takes precedence).",
    )
    sponsor: Optional[StrictBool] = Field(
        default=None,
        description="Whether to use Cobo Gasless (Fee Station) to cover gas fees. `true`: gas fees are sponsored. `false`: gas fees are paid from the wallet. Defaults to `true` for human-owned wallets.",
    )
    gas_provider: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(
        default=None,
        description="The gas provider to use for sponsored transactions. If omitted, the server default is used.",
    )
    description: Optional[Annotated[str, Field(strict=True, max_length=512)]] = Field(
        default=None,
        description="Optional note stored locally and sent to WaaS as the transaction `description` (contract call).",
    )
    __properties: ClassVar[List[str]] = [
        "chain_id",
        "contract_addr",
        "value",
        "calldata",
        "instructions",
        "address_lookup_table_accounts",
        "request_id",
        "fee",
        "src_addr",
        "sponsor",
        "gas_provider",
        "description",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContractCallCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in instructions (list)
        _items = []
        if self.instructions:
            for _item in self.instructions:
                if _item:
                    _items.append(_item.to_dict())
            _dict["instructions"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in address_lookup_table_accounts (list)
        _items = []
        if self.address_lookup_table_accounts:
            for _item in self.address_lookup_table_accounts:
                if _item:
                    _items.append(_item.to_dict())
            _dict["address_lookup_table_accounts"] = _items
        # override the default output from pydantic by calling `to_dict()` of fee
        if self.fee:
            _dict["fee"] = self.fee.to_dict()
        # set to None if fee (nullable) is None
        # and model_fields_set contains the field
        if self.fee is None and "fee" in self.model_fields_set:
            _dict["fee"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContractCallCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "chain_id": obj.get("chain_id"),
                "contract_addr": obj.get("contract_addr"),
                "value": obj.get("value") if obj.get("value") is not None else "0",
                "calldata": obj.get("calldata"),
                "instructions": [SolInstruction.from_dict(_item) for _item in obj["instructions"]]
                if obj.get("instructions") is not None
                else None,
                "address_lookup_table_accounts": [
                    SolAddressLookupTableAccount.from_dict(_item)
                    for _item in obj["address_lookup_table_accounts"]
                ]
                if obj.get("address_lookup_table_accounts") is not None
                else None,
                "request_id": obj.get("request_id"),
                "fee": FeeRequest.from_dict(obj["fee"]) if obj.get("fee") is not None else None,
                "src_addr": obj.get("src_addr"),
                "sponsor": obj.get("sponsor"),
                "gas_provider": obj.get("gas_provider"),
                "description": obj.get("description"),
            }
        )
        return _obj
