# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self


class DelegationUsageLimitSummary(BaseModel):
    """
    DelegationUsageLimitSummary
    """  # noqa: E501

    operation_type: StrictStr = Field(
        description="Operation type for this limit, for example `transfer` or `contract_call`."
    )
    window: StrictStr = Field(
        description="Rolling window key in counter terms, for example `hourly` or `daily`."
    )
    metric: StrictStr = Field(
        description="Metric dimension for this limit, for example `count`, `value`, or `usd_value`."
    )
    used: StrictStr = Field(description="Current usage in this window, as a decimal string.")
    limit: StrictStr = Field(description="Configured threshold value, as a decimal string.")
    remaining: StrictStr = Field(
        description="Remaining available quota in this window, as a decimal string."
    )
    __properties: ClassVar[List[str]] = [
        "operation_type",
        "window",
        "metric",
        "used",
        "limit",
        "remaining",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DelegationUsageLimitSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DelegationUsageLimitSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "operation_type": obj.get("operation_type"),
                "window": obj.get("window"),
                "metric": obj.get("metric"),
                "used": obj.get("used"),
                "limit": obj.get("limit"),
                "remaining": obj.get("remaining"),
            }
        )
        return _obj
