# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cobo_agentic_wallet_api.models.delegation_permission import DelegationPermission
from cobo_agentic_wallet_api.models.inline_policy_create import InlinePolicyCreate
from typing import Set
from typing_extensions import Self


class DelegationCreate(BaseModel):
    """
    Request payload for creating a delegation.
    """  # noqa: E501

    operator_id: StrictStr = Field(description="The ID of the principal receiving wallet access.")
    wallet_id: StrictStr = Field(
        description="The wallet to delegate access to. The wallet ID can be retrieved by calling the List all wallets operation."
    )
    permissions: Annotated[List[DelegationPermission], Field(min_length=1)] = Field(
        description="The permissions to grant. At least one is required. Valid values: `read:wallet`, `operator`, `write:transaction`, `write:transfer`, `write:contract_call`, `write:manage`, `write:policy`."
    )
    policies: Optional[List[InlinePolicyCreate]] = Field(
        default=None,
        description="Optional delegation-scoped policies to create alongside the delegation.",
    )
    expires_at: Optional[datetime] = Field(
        default=None,
        description="The expiry timestamp for this delegation, in ISO 8601 format. If omitted, the delegation does not expire.",
    )
    __properties: ClassVar[List[str]] = [
        "operator_id",
        "wallet_id",
        "permissions",
        "policies",
        "expires_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DelegationCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in policies (list)
        _items = []
        if self.policies:
            for _item in self.policies:
                if _item:
                    _items.append(_item.to_dict())
            _dict["policies"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DelegationCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "operator_id": obj.get("operator_id"),
                "wallet_id": obj.get("wallet_id"),
                "permissions": obj.get("permissions"),
                "policies": [InlinePolicyCreate.from_dict(_item) for _item in obj["policies"]]
                if obj.get("policies") is not None
                else None,
                "expires_at": obj.get("expires_at"),
            }
        )
        return _obj
