# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DelegationPermission(str, Enum):
    """
    Delegation permission vocabulary.
    """

    """
    allowed enum values
    """
    OPERATOR = "operator"
    READ_COLON_WALLET = "read:wallet"
    WRITE_COLON_TRANSACTION = "write:transaction"
    WRITE_COLON_TRANSFER = "write:transfer"
    WRITE_COLON_CONTRACT_CALL = "write:contract_call"
    WRITE_COLON_MESSAGE_SIGN = "write:message_sign"
    WRITE_COLON_MANAGE = "write:manage"
    WRITE_COLON_POLICY = "write:policy"

    _UNKNOWN_FALLBACK = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DelegationPermission from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls._UNKNOWN_FALLBACK

    @classmethod
    def to_choices(cls) -> list[tuple[str, str]]:
        return [(member.value, member.name) for member in cls if member != cls._UNKNOWN_FALLBACK]
