# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_agentic_wallet_api.models.delegation_usage_limit_summary import (
    DelegationUsageLimitSummary,
)
from typing import Set
from typing_extensions import Self


class DelegationSpendSummary(BaseModel):
    """
    DelegationSpendSummary
    """  # noqa: E501

    delegation_id: StrictStr = Field(description="The delegation ID.")
    operator_id: StrictStr = Field(description="The operator's principal ID.")
    frozen: StrictBool = Field(
        description="Whether the delegation is currently frozen. `true`: frozen. `false`: active."
    )
    daily_spent: StrictStr = Field(
        description="The total amount spent today by this delegation, as a decimal string."
    )
    daily_limit: Optional[StrictStr] = Field(
        default=None,
        description="The daily spending limit for this delegation. Null if no daily limit is set.",
    )
    monthly_spent: StrictStr = Field(
        description="The total amount spent this month by this delegation, as a decimal string."
    )
    monthly_limit: Optional[StrictStr] = Field(
        default=None,
        description="The monthly spending limit for this delegation. Null if no monthly limit is set.",
    )
    usage_limits_summary: Optional[List[DelegationUsageLimitSummary]] = Field(
        default=None,
        description="Per-window usage limit snapshots for delegation policies, including used/limit/remaining.",
    )
    __properties: ClassVar[List[str]] = [
        "delegation_id",
        "operator_id",
        "frozen",
        "daily_spent",
        "daily_limit",
        "monthly_spent",
        "monthly_limit",
        "usage_limits_summary",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DelegationSpendSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in usage_limits_summary (list)
        _items = []
        if self.usage_limits_summary:
            for _item in self.usage_limits_summary:
                if _item:
                    _items.append(_item.to_dict())
            _dict["usage_limits_summary"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DelegationSpendSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "delegation_id": obj.get("delegation_id"),
                "operator_id": obj.get("operator_id"),
                "frozen": obj.get("frozen"),
                "daily_spent": obj.get("daily_spent"),
                "daily_limit": obj.get("daily_limit"),
                "monthly_spent": obj.get("monthly_spent"),
                "monthly_limit": obj.get("monthly_limit"),
                "usage_limits_summary": [
                    DelegationUsageLimitSummary.from_dict(_item)
                    for _item in obj["usage_limits_summary"]
                ]
                if obj.get("usage_limits_summary") is not None
                else None,
            }
        )
        return _obj
