# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_agentic_wallet_api.models.delegation_status import DelegationStatus
from typing import Set
from typing_extensions import Self


class DelegationRead(BaseModel):
    """
    Delegation response payload.
    """  # noqa: E501

    id: StrictStr = Field(description="The delegation ID.")
    owner_id: StrictStr = Field(
        description="The ID of the principal that created this delegation (the wallet owner)."
    )
    operator_id: StrictStr = Field(description="The ID of the principal that received access.")
    wallet_id: StrictStr = Field(description="The wallet this delegation grants access to.")
    permissions: List[StrictStr] = Field(
        description="The list of permissions granted by this delegation."
    )
    policies: Optional[List[Dict[str, Any]]] = Field(
        default=None, description="Delegation-scoped policies associated with this delegation."
    )
    status: DelegationStatus = Field(
        description="The delegation status. Possible values: `active`, `revoked`, `expired`."
    )
    frozen: Optional[StrictBool] = Field(
        default=False,
        description="Whether this delegation is currently frozen. `true`: the operator cannot perform any actions. `false`: the delegation is active.",
    )
    freeze_reason: Optional[StrictStr] = Field(
        default=None, description="The reason the delegation was frozen, if set."
    )
    frozen_at: Optional[datetime] = Field(
        default=None,
        description="The timestamp when the delegation was frozen, in ISO 8601 format. Null if not frozen.",
    )
    expires_at: Optional[datetime] = None
    revoked_at: Optional[datetime] = None
    created_at: datetime = Field(
        description="The timestamp when the delegation was created, in ISO 8601 format."
    )
    updated_at: datetime = Field(
        description="The timestamp when the delegation was last updated, in ISO 8601 format."
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "owner_id",
        "operator_id",
        "wallet_id",
        "permissions",
        "policies",
        "status",
        "frozen",
        "freeze_reason",
        "frozen_at",
        "expires_at",
        "revoked_at",
        "created_at",
        "updated_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DelegationRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict["expires_at"] = None

        # set to None if revoked_at (nullable) is None
        # and model_fields_set contains the field
        if self.revoked_at is None and "revoked_at" in self.model_fields_set:
            _dict["revoked_at"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DelegationRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "owner_id": obj.get("owner_id"),
                "operator_id": obj.get("operator_id"),
                "wallet_id": obj.get("wallet_id"),
                "permissions": obj.get("permissions"),
                "policies": obj.get("policies"),
                "status": obj.get("status"),
                "frozen": obj.get("frozen") if obj.get("frozen") is not None else False,
                "freeze_reason": obj.get("freeze_reason"),
                "frozen_at": obj.get("frozen_at"),
                "expires_at": obj.get("expires_at"),
                "revoked_at": obj.get("revoked_at"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
            }
        )
        return _obj
