# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Set
from typing_extensions import Self


class EIP1559FeeRequest(BaseModel):
    """
    Optional EIP-1559 fee parameters for transfers.
    """  # noqa: E501

    fee_type: Optional[StrictStr] = Field(
        default="EVM_EIP_1559", description="The fee type. Must be `EVM_EIP_1559`."
    )
    max_fee_per_gas: Annotated[str, Field(min_length=1, strict=True)] = Field(
        description="The maximum total fee per gas, in wei."
    )
    max_priority_fee_per_gas: Annotated[str, Field(min_length=1, strict=True)] = Field(
        description="The maximum priority fee (tip) per gas, in wei."
    )
    gas_limit: Annotated[str, Field(min_length=1, strict=True)] = Field(
        description="The gas limit for this transaction."
    )
    token_id: Annotated[str, Field(min_length=1, strict=True, max_length=100)] = Field(
        description="The token ID for fee payment."
    )
    __properties: ClassVar[List[str]] = [
        "fee_type",
        "max_fee_per_gas",
        "max_priority_fee_per_gas",
        "gas_limit",
        "token_id",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EIP1559FeeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EIP1559FeeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "fee_type": obj.get("fee_type")
                if obj.get("fee_type") is not None
                else "EVM_EIP_1559",
                "max_fee_per_gas": obj.get("max_fee_per_gas"),
                "max_priority_fee_per_gas": obj.get("max_priority_fee_per_gas"),
                "gas_limit": obj.get("gas_limit"),
                "token_id": obj.get("token_id"),
            }
        )
        return _obj
