# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.2.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cobo_agentic_wallet_api.models.sol_address_lookup_table_account import (
    SolAddressLookupTableAccount,
)
from cobo_agentic_wallet_api.models.sol_instruction import SolInstruction
from typing import Set
from typing_extensions import Self


class EstimateContractCallFeeRequest(BaseModel):
    """
    Request payload for contract-call fee estimation.
    """  # noqa: E501

    chain_id: Annotated[str, Field(min_length=1, strict=True, max_length=100)] = Field(
        description="The Cobo chain ID for this contract call (for example, `SETH`, `BASE_ETH`, `SOL`)."
    )
    contract_addr: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None, description="The EVM contract address to call. Required for EVM chains."
    )
    value: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100)]] = Field(
        default="0",
        description="The ETH value to send with the call, in whole token units (not wei), as a decimal string. Defaults to `0`.",
    )
    calldata: Optional[Annotated[str, Field(strict=True, max_length=8192)]] = Field(
        default=None, description="The ABI-encoded calldata as a hex string."
    )
    instructions: Optional[List[SolInstruction]] = Field(
        default=None, description="Solana instructions for this call. Required for Solana chains."
    )
    address_lookup_table_accounts: Optional[List[SolAddressLookupTableAccount]] = Field(
        default=None, description="Optional Solana address lookup table accounts."
    )
    src_addr: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None,
        description="The source address. If omitted, the wallet's most recently created address for this chain is used.",
    )
    __properties: ClassVar[List[str]] = [
        "chain_id",
        "contract_addr",
        "value",
        "calldata",
        "instructions",
        "address_lookup_table_accounts",
        "src_addr",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EstimateContractCallFeeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in instructions (list)
        _items = []
        if self.instructions:
            for _item in self.instructions:
                if _item:
                    _items.append(_item.to_dict())
            _dict["instructions"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in address_lookup_table_accounts (list)
        _items = []
        if self.address_lookup_table_accounts:
            for _item in self.address_lookup_table_accounts:
                if _item:
                    _items.append(_item.to_dict())
            _dict["address_lookup_table_accounts"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EstimateContractCallFeeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "chain_id": obj.get("chain_id"),
                "contract_addr": obj.get("contract_addr"),
                "value": obj.get("value") if obj.get("value") is not None else "0",
                "calldata": obj.get("calldata"),
                "instructions": [SolInstruction.from_dict(_item) for _item in obj["instructions"]]
                if obj.get("instructions") is not None
                else None,
                "address_lookup_table_accounts": [
                    SolAddressLookupTableAccount.from_dict(_item)
                    for _item in obj["address_lookup_table_accounts"]
                ]
                if obj.get("address_lookup_table_accounts") is not None
                else None,
                "src_addr": obj.get("src_addr"),
            }
        )
        return _obj
