# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.2.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_agentic_wallet_api.models.fee_estimate_read import FeeEstimateRead
from typing import Set
from typing_extensions import Self


class EstimateTransferFeeRead(BaseModel):
    """
    Fee estimation response payload.
    """  # noqa: E501

    fee_type: Optional[StrictStr] = Field(
        default=None, description="The fee model type (for example, `EVM_EIP_1559`, `SOL`)."
    )
    token_id: Optional[StrictStr] = Field(default=None, description="The token used to pay fees.")
    recommended: Optional[FeeEstimateRead] = Field(
        default=None, description="The recommended fee estimate, balancing speed and cost."
    )
    slow: Optional[FeeEstimateRead] = Field(
        default=None, description="A lower-cost fee estimate with slower confirmation."
    )
    fast: Optional[FeeEstimateRead] = Field(
        default=None, description="A higher-cost fee estimate with faster confirmation."
    )
    __properties: ClassVar[List[str]] = ["fee_type", "token_id", "recommended", "slow", "fast"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EstimateTransferFeeRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of recommended
        if self.recommended:
            _dict["recommended"] = self.recommended.to_dict()
        # override the default output from pydantic by calling `to_dict()` of slow
        if self.slow:
            _dict["slow"] = self.slow.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fast
        if self.fast:
            _dict["fast"] = self.fast.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EstimateTransferFeeRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "fee_type": obj.get("fee_type"),
                "token_id": obj.get("token_id"),
                "recommended": FeeEstimateRead.from_dict(obj["recommended"])
                if obj.get("recommended") is not None
                else None,
                "slow": FeeEstimateRead.from_dict(obj["slow"])
                if obj.get("slow") is not None
                else None,
                "fast": FeeEstimateRead.from_dict(obj["fast"])
                if obj.get("fast") is not None
                else None,
            }
        )
        return _obj
