# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cobo_agentic_wallet_api.models.hire_participant_role import HireParticipantRole
from cobo_agentic_wallet_api.models.hire_settlement_type import HireSettlementType
from typing import Set
from typing_extensions import Self


class HireSettlementRecord(BaseModel):
    """
    Stored settlement result.
    """  # noqa: E501

    settlement_type: HireSettlementType
    payment_tx_hash: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    refund_tx_hash: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    amount: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    client_amount: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    service_amount: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    token: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    chain: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    signed_by: Annotated[List[HireParticipantRole], Field(min_length=1)]
    settled_at: datetime
    __properties: ClassVar[List[str]] = [
        "settlement_type",
        "payment_tx_hash",
        "refund_tx_hash",
        "amount",
        "client_amount",
        "service_amount",
        "token",
        "chain",
        "signed_by",
        "settled_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HireSettlementRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HireSettlementRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "settlement_type": obj.get("settlement_type"),
                "payment_tx_hash": obj.get("payment_tx_hash"),
                "refund_tx_hash": obj.get("refund_tx_hash"),
                "amount": obj.get("amount"),
                "client_amount": obj.get("client_amount"),
                "service_amount": obj.get("service_amount"),
                "token": obj.get("token"),
                "chain": obj.get("chain"),
                "signed_by": obj.get("signed_by"),
                "settled_at": obj.get("settled_at"),
            }
        )
        return _obj
