# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_agentic_wallet_api.models.hire_settlement_record import HireSettlementRecord
from typing import Set
from typing_extensions import Self


class HireSettlementProposalRead(BaseModel):
    """
    Settlement proposal snapshot returned from the API.
    """  # noqa: E501

    id: StrictStr
    proposed_by: StrictStr
    client_amount: StrictStr
    service_amount: StrictStr
    message: Optional[StrictStr] = None
    status: StrictStr
    matched_with_proposal_id: Optional[StrictStr] = None
    applied_settlement: Optional[HireSettlementRecord] = None
    applied_at: Optional[datetime] = None
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = [
        "id",
        "proposed_by",
        "client_amount",
        "service_amount",
        "message",
        "status",
        "matched_with_proposal_id",
        "applied_settlement",
        "applied_at",
        "created_at",
        "updated_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HireSettlementProposalRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of applied_settlement
        if self.applied_settlement:
            _dict["applied_settlement"] = self.applied_settlement.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HireSettlementProposalRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "proposed_by": obj.get("proposed_by"),
                "client_amount": obj.get("client_amount"),
                "service_amount": obj.get("service_amount"),
                "message": obj.get("message"),
                "status": obj.get("status"),
                "matched_with_proposal_id": obj.get("matched_with_proposal_id"),
                "applied_settlement": HireSettlementRecord.from_dict(obj["applied_settlement"])
                if obj.get("applied_settlement") is not None
                else None,
                "applied_at": obj.get("applied_at"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
            }
        )
        return _obj
