# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_agentic_wallet_api.models.artifact import Artifact
from cobo_agentic_wallet_api.models.hire_arbitration_ruling_record import (
    HireArbitrationRulingRecord,
)
from cobo_agentic_wallet_api.models.hire_dispute_response_record import HireDisputeResponseRecord
from typing import Set
from typing_extensions import Self


class HireDisputeRead(BaseModel):
    """
    Dispute snapshot returned from the API.
    """  # noqa: E501

    dispute_id: StrictStr
    opened_by: StrictStr
    dispute_type: StrictStr
    requested_resolution: StrictStr
    evidence: Optional[List[Artifact]] = None
    message: StrictStr
    status: StrictStr
    response: Optional[HireDisputeResponseRecord] = None
    ruling: Optional[HireArbitrationRulingRecord] = None
    response_received_at: Optional[datetime] = None
    ruled_at: Optional[datetime] = None
    settled_at: Optional[datetime] = None
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = [
        "dispute_id",
        "opened_by",
        "dispute_type",
        "requested_resolution",
        "evidence",
        "message",
        "status",
        "response",
        "ruling",
        "response_received_at",
        "ruled_at",
        "settled_at",
        "created_at",
        "updated_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HireDisputeRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in evidence (list)
        _items = []
        if self.evidence:
            for _item in self.evidence:
                if _item:
                    _items.append(_item.to_dict())
            _dict["evidence"] = _items
        # override the default output from pydantic by calling `to_dict()` of response
        if self.response:
            _dict["response"] = self.response.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ruling
        if self.ruling:
            _dict["ruling"] = self.ruling.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HireDisputeRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "dispute_id": obj.get("dispute_id"),
                "opened_by": obj.get("opened_by"),
                "dispute_type": obj.get("dispute_type"),
                "requested_resolution": obj.get("requested_resolution"),
                "evidence": [Artifact.from_dict(_item) for _item in obj["evidence"]]
                if obj.get("evidence") is not None
                else None,
                "message": obj.get("message"),
                "status": obj.get("status"),
                "response": HireDisputeResponseRecord.from_dict(obj["response"])
                if obj.get("response") is not None
                else None,
                "ruling": HireArbitrationRulingRecord.from_dict(obj["ruling"])
                if obj.get("ruling") is not None
                else None,
                "response_received_at": obj.get("response_received_at"),
                "ruled_at": obj.get("ruled_at"),
                "settled_at": obj.get("settled_at"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
            }
        )
        return _obj
