# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cobo_agentic_wallet_api.models.artifact import Artifact
from cobo_agentic_wallet_api.models.hire_resolution import HireResolution
from cobo_agentic_wallet_api.models.hire_settlement_split import HireSettlementSplit
from typing import Set
from typing_extensions import Self


class HireDisputeResponseRecord(BaseModel):
    """
    Stored dispute response payload.
    """  # noqa: E501

    dispute_id: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    counter_evidence: Optional[List[Artifact]] = None
    proposed_resolution: Optional[HireResolution] = None
    custom_split: Optional[HireSettlementSplit] = None
    message: Annotated[str, Field(min_length=1, strict=True, max_length=4000)]
    responded_at: datetime
    __properties: ClassVar[List[str]] = [
        "dispute_id",
        "counter_evidence",
        "proposed_resolution",
        "custom_split",
        "message",
        "responded_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HireDisputeResponseRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in counter_evidence (list)
        _items = []
        if self.counter_evidence:
            for _item in self.counter_evidence:
                if _item:
                    _items.append(_item.to_dict())
            _dict["counter_evidence"] = _items
        # override the default output from pydantic by calling `to_dict()` of custom_split
        if self.custom_split:
            _dict["custom_split"] = self.custom_split.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HireDisputeResponseRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "dispute_id": obj.get("dispute_id"),
                "counter_evidence": [Artifact.from_dict(_item) for _item in obj["counter_evidence"]]
                if obj.get("counter_evidence") is not None
                else None,
                "proposed_resolution": obj.get("proposed_resolution"),
                "custom_split": HireSettlementSplit.from_dict(obj["custom_split"])
                if obj.get("custom_split") is not None
                else None,
                "message": obj.get("message"),
                "responded_at": obj.get("responded_at"),
            }
        )
        return _obj
