# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class KeyShareHolderGroupStatus(str, Enum):
    """
    Aligned with ``cobo_waas2.models.key_share_holder_group_status.KeyShareHolderGroupStatus``.
    """

    """
    allowed enum values
    """
    NEW = "New"
    VALID = "Valid"
    UNAVAILABLE = "Unavailable"

    _UNKNOWN_FALLBACK = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of KeyShareHolderGroupStatus from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls._UNKNOWN_FALLBACK

    @classmethod
    def to_choices(cls) -> list[tuple[str, str]]:
        return [(member.value, member.name) for member in cls if member != cls._UNKNOWN_FALLBACK]
