# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cobo_agentic_wallet_api.models.message_sign_dest_type import MessageSignDestType
from typing import Set
from typing_extensions import Self


class MessageSignCreate(BaseModel):
    """
    Request payload for message signing.  Currently supports EIP-712 structured data signing. The ``destination_type`` field determines which payload field is required.
    """  # noqa: E501

    chain_id: StrictStr = Field(description="CAW/WaaS chain ID, e.g. 'ETH', 'SETH'")
    destination_type: Optional[MessageSignDestType] = Field(
        default=None, description="Signing type. Determines which payload field is used."
    )
    eip712_typed_data: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Complete EIP-712 typed data: {domain, types, primaryType, message}. Required when destination_type='eip712'.",
    )
    source_address: Optional[StrictStr] = Field(
        default=None,
        description="Specific address to sign with. If omitted, the wallet's most recently created address for this chain is used.",
    )
    description: Optional[Annotated[str, Field(strict=True, max_length=512)]] = None
    sync: Optional[StrictBool] = Field(
        default=True,
        description="True: wait for signature before responding. False: return immediately after submit.",
    )
    request_id: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(
        default=None, description="Idempotency key. Replays are scoped to the same principal."
    )
    __properties: ClassVar[List[str]] = [
        "chain_id",
        "destination_type",
        "eip712_typed_data",
        "source_address",
        "description",
        "sync",
        "request_id",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessageSignCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessageSignCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "chain_id": obj.get("chain_id"),
                "destination_type": obj.get("destination_type"),
                "eip712_typed_data": obj.get("eip712_typed_data"),
                "source_address": obj.get("source_address"),
                "description": obj.get("description"),
                "sync": obj.get("sync") if obj.get("sync") is not None else True,
                "request_id": obj.get("request_id"),
            }
        )
        return _obj
