# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class MppSessionInfo(BaseModel):
    """
    MPP session details returned by the backend after a successful channel open action.
    """  # noqa: E501

    payer_address: StrictStr = Field(
        description="On-chain address of the payer who opened the payment channel."
    )
    chain_id: StrictStr = Field(
        description="Cobo chain ID on which the payment channel was opened (e.g. 'ETH' for Ethereum mainnet). Call the List supported chains operation (GET /metadata/chains) to retrieve all supported chain IDs."
    )
    channel_id: Optional[StrictStr] = Field(
        default=None,
        description="Unique identifier of the opened payment channel. May be absent if the channel is not yet confirmed on-chain.",
    )
    __properties: ClassVar[List[str]] = ["payer_address", "chain_id", "channel_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MppSessionInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MppSessionInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "payer_address": obj.get("payer_address"),
                "chain_id": obj.get("chain_id"),
                "channel_id": obj.get("channel_id"),
            }
        )
        return _obj
