# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class MppChallenge(BaseModel):
    """
    Parsed MPP Payment challenge from WWW-Authenticate header.
    """  # noqa: E501

    id: StrictStr
    realm: StrictStr
    method: StrictStr
    intent: StrictStr
    request: Dict[str, Any]
    request_b64: StrictStr
    expires: Optional[StrictStr] = ""
    description: Optional[StrictStr] = ""
    __properties: ClassVar[List[str]] = [
        "id",
        "realm",
        "method",
        "intent",
        "request",
        "request_b64",
        "expires",
        "description",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MppChallenge from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MppChallenge from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "realm": obj.get("realm"),
                "method": obj.get("method"),
                "intent": obj.get("intent"),
                "request": obj.get("request"),
                "request_b64": obj.get("request_b64"),
                "expires": obj.get("expires") if obj.get("expires") is not None else "",
                "description": obj.get("description") if obj.get("description") is not None else "",
            }
        )
        return _obj
