# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cobo_agentic_wallet_api.models.hire_pact_spec_patch_output import HirePactSpecPatchOutput
from cobo_agentic_wallet_api.models.hire_participant_role import HireParticipantRole
from typing import Set
from typing_extensions import Self


class NegotiatedSpecPatchEntryOutput(BaseModel):
    """
    Chronological record of negotiated spec changes.
    """  # noqa: E501

    actor_role: HireParticipantRole
    patch: HirePactSpecPatchOutput
    message: Optional[Annotated[str, Field(strict=True, max_length=4000)]] = None
    created_at: datetime
    __properties: ClassVar[List[str]] = ["actor_role", "patch", "message", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NegotiatedSpecPatchEntryOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of patch
        if self.patch:
            _dict["patch"] = self.patch.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NegotiatedSpecPatchEntryOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "actor_role": obj.get("actor_role"),
                "patch": HirePactSpecPatchOutput.from_dict(obj["patch"])
                if obj.get("patch") is not None
                else None,
                "message": obj.get("message"),
                "created_at": obj.get("created_at"),
            }
        )
        return _obj
