# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.2.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_agentic_wallet_api.models.completion_condition import CompletionCondition
from cobo_agentic_wallet_api.models.inline_policy_create import InlinePolicyCreate
from typing import Set
from typing_extensions import Self


class PactSpecOutput(BaseModel):
    """
    The core pact specification — defines policies and completion conditions.
    """  # noqa: E501

    policies: Optional[List[InlinePolicyCreate]] = Field(
        default=None, description="Policy rules constraining the operator's actions."
    )
    completion_conditions: Optional[List[CompletionCondition]] = Field(
        default=None,
        description="Conditions that trigger automatic pact completion (any-of semantics).",
    )
    execution_plan: Optional[StrictStr] = Field(
        default=None,
        description="Free-form execution plan derived from the intent, in markdown format. Presented to the owner during approval review so they can understand exactly what the operator will do. Suggested sections: # Summary, # Contract Operations, # Risk Controls, # Schedule.",
    )
    __properties: ClassVar[List[str]] = ["policies", "completion_conditions", "execution_plan"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PactSpecOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in policies (list)
        _items = []
        if self.policies:
            for _item in self.policies:
                if _item:
                    _items.append(_item.to_dict())
            _dict["policies"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in completion_conditions (list)
        _items = []
        if self.completion_conditions:
            for _item in self.completion_conditions:
                if _item:
                    _items.append(_item.to_dict())
            _dict["completion_conditions"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PactSpecOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "policies": [InlinePolicyCreate.from_dict(_item) for _item in obj["policies"]]
                if obj.get("policies") is not None
                else None,
                "completion_conditions": [
                    CompletionCondition.from_dict(_item) for _item in obj["completion_conditions"]
                ]
                if obj.get("completion_conditions") is not None
                else None,
                "execution_plan": obj.get("execution_plan"),
            }
        )
        return _obj
