# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.2.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_agentic_wallet_api.models.pact_status import PactStatus
from cobo_agentic_wallet_api.models.principal_read import PrincipalRead
from typing import Set
from typing_extensions import Self


class PactSummary(BaseModel):
    """
    Lightweight pact item for list responses.
    """  # noqa: E501

    id: StrictStr = Field(description="Pact ID.")
    name: StrictStr = Field(description="Pact name.")
    intent: StrictStr = Field(description="Natural language intent.")
    original_intent: Optional[StrictStr] = Field(
        default=None,
        description="Raw user input that originated this pact request. For multi-turn conversations, messages are concatenated.",
    )
    status: PactStatus = Field(description="Current pact status.")
    wallet_id: StrictStr = Field(description="Target wallet ID.")
    is_default: Optional[StrictBool] = Field(
        default=False, description="Whether this is the default pact created during provisioning."
    )
    created_at: datetime = Field(description="When the pact was submitted.")
    expires_at: Optional[datetime] = None
    recipe_slugs: Optional[List[StrictStr]] = Field(
        default=None, description="Slugs of recipes associated with this pact."
    )
    operator: Optional[PrincipalRead] = Field(
        default=None,
        description="Operator principal. Null if the principal row is missing (e.g. legacy data).",
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "name",
        "intent",
        "original_intent",
        "status",
        "wallet_id",
        "is_default",
        "created_at",
        "expires_at",
        "recipe_slugs",
        "operator",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PactSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of operator
        if self.operator:
            _dict["operator"] = self.operator.to_dict()
        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict["expires_at"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PactSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "intent": obj.get("intent"),
                "original_intent": obj.get("original_intent"),
                "status": obj.get("status"),
                "wallet_id": obj.get("wallet_id"),
                "is_default": obj.get("is_default") if obj.get("is_default") is not None else False,
                "created_at": obj.get("created_at"),
                "expires_at": obj.get("expires_at"),
                "recipe_slugs": obj.get("recipe_slugs"),
                "operator": PrincipalRead.from_dict(obj["operator"])
                if obj.get("operator") is not None
                else None,
            }
        )
        return _obj
