# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class PaginationMeta(BaseModel):
    """
    Pagination metadata for list responses.  Supports both legacy offset-based and cursor-based pagination. Cursor fields (``has_more``, ``after``, ``before``) are populated for cursor-paginated endpoints.  Legacy fields (``offset``, ``limit``) are populated when the caller uses the deprecated ``offset`` parameter.
    """  # noqa: E501

    total: Optional[StrictInt] = None
    offset: Optional[StrictInt] = None
    limit: Optional[StrictInt] = None
    has_more: Optional[StrictBool] = None
    after: Optional[StrictStr] = None
    before: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["total", "offset", "limit", "has_more", "after", "before"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaginationMeta from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaginationMeta from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "total": obj.get("total"),
                "offset": obj.get("offset"),
                "limit": obj.get("limit"),
                "has_more": obj.get("has_more"),
                "after": obj.get("after"),
                "before": obj.get("before"),
            }
        )
        return _obj
