# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.2.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cobo_agentic_wallet_api.models.principal_type import PrincipalType
from typing import Set
from typing_extensions import Self


class PrincipalCreate(BaseModel):
    """
    Request payload for creating a principal.
    """  # noqa: E501

    external_id: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(
        description="Your system's identifier for this principal (for example, a user ID). Must be unique. Max 255 characters."
    )
    type: PrincipalType = Field(
        description="The principal type. Possible values: `human`, `agent`."
    )
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(
        description="The display name for this principal. Max 255 characters."
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default=None, description="Arbitrary key-value metadata to associate with the principal."
    )
    __properties: ClassVar[List[str]] = ["external_id", "type", "name", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PrincipalCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PrincipalCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "external_id": obj.get("external_id"),
                "type": obj.get("type"),
                "name": obj.get("name"),
                "metadata": obj.get("metadata"),
            }
        )
        return _obj
