# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.2.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class ProvisionResponse(BaseModel):
    """
    Provisioning result for both token and agent-first modes.
    """  # noqa: E501

    agent_id: StrictStr = Field(description="The agent's principal ID.")
    api_key: StrictStr = Field(
        description="The API key for the provisioned agent. Store it securely — it is only returned once."
    )
    status: StrictStr = Field(
        description="The agent's current status. `active`: the agent is ready for use. `temporary`: deprecated legacy value kept for backward compatibility and planned for removal in a future major release."
    )
    owner_id: Optional[StrictStr] = Field(
        default=None,
        description="The ID of the owner principal when available (for example in token-based provisioning).",
    )
    onboarding_session_id: Optional[StrictStr] = Field(
        default=None,
        description="The onboarding session ID. Only set during Cobo Agentic Wallet app provisioning flows.",
    )
    __properties: ClassVar[List[str]] = [
        "agent_id",
        "api_key",
        "status",
        "owner_id",
        "onboarding_session_id",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["active", "temporary"]):
            raise ValueError("must be one of enum values ('active', 'temporary')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProvisionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProvisionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "agent_id": obj.get("agent_id"),
                "api_key": obj.get("api_key"),
                "status": obj.get("status"),
                "owner_id": obj.get("owner_id"),
                "onboarding_session_id": obj.get("onboarding_session_id"),
            }
        )
        return _obj
