# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_agentic_wallet_api.models.recipe_status import RecipeStatus
from typing import Set
from typing_extensions import Self


class RecipeRead(BaseModel):
    """
    Recipe library entry returned from the API.
    """  # noqa: E501

    id: StrictStr
    slug: StrictStr
    title: StrictStr
    description: StrictStr
    example_prompts: List[StrictStr] = Field(
        description="Sample prompts that demonstrate how to invoke this recipe."
    )
    chains: List[StrictStr] = Field(
        description="Blockchain identifiers this recipe applies to (for example, `ethereum`, `solana`)."
    )
    tags: List[StrictStr] = Field(description="Descriptive tags for filtering and discovery.")
    category: List[StrictStr] = Field(
        description="Category labels used to group recipes in the library."
    )
    icon: Optional[str] = None
    author_name: StrictStr
    status: RecipeStatus = Field(
        description="Publication status of the recipe. Possible values: `draft`, `pending_review`, `published`, `rejected`."
    )
    featured: StrictBool = Field(
        description="When `true`, the recipe is highlighted in the library. When `false`, it appears in the standard listing."
    )
    verified: StrictBool = Field(
        description="When `true`, the recipe has been reviewed and verified by the platform. When `false`, it is community-submitted."
    )
    view_count: StrictInt = Field(description="Total number of times this recipe has been viewed.")
    use_count: StrictInt = Field(
        description="Total number of times this recipe has been used to start a task."
    )
    share_count: StrictInt = Field(description="Total number of times this recipe has been shared.")
    search_count: StrictInt = Field(
        description="Total number of times this recipe has appeared in search results."
    )
    locale: StrictStr
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = [
        "id",
        "slug",
        "title",
        "description",
        "example_prompts",
        "chains",
        "tags",
        "category",
        "icon",
        "author_name",
        "status",
        "featured",
        "verified",
        "view_count",
        "use_count",
        "share_count",
        "search_count",
        "locale",
        "created_at",
        "updated_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecipeRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if icon (nullable) is None
        # and model_fields_set contains the field
        if self.icon is None and "icon" in self.model_fields_set:
            _dict["icon"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecipeRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "slug": obj.get("slug"),
                "title": obj.get("title"),
                "description": obj.get("description"),
                "example_prompts": obj.get("example_prompts"),
                "chains": obj.get("chains"),
                "tags": obj.get("tags"),
                "category": obj.get("category"),
                "icon": obj.get("icon"),
                "author_name": obj.get("author_name"),
                "status": obj.get("status"),
                "featured": obj.get("featured"),
                "verified": obj.get("verified"),
                "view_count": obj.get("view_count"),
                "use_count": obj.get("use_count"),
                "share_count": obj.get("share_count"),
                "search_count": obj.get("search_count"),
                "locale": obj.get("locale"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
            }
        )
        return _obj
