# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Set
from typing_extensions import Self


class RecipeSubmissionCreate(BaseModel):
    """
    RecipeSubmissionCreate
    """  # noqa: E501

    slug: Annotated[str, Field(min_length=1, strict=True, max_length=128)]
    title: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    description: Annotated[str, Field(min_length=1, strict=True)]
    content_markdown: Optional[StrictStr] = ""
    chains: Optional[List[StrictStr]] = None
    tokens: Optional[Dict[str, Dict[str, StrictStr]]] = None
    tags: Optional[List[StrictStr]] = None
    category: Optional[List[StrictStr]] = None
    example_prompts: Optional[List[StrictStr]] = None
    icon: Optional[Annotated[str, Field(strict=True, max_length=512)]] = Field(
        default="https://d.cobo.com/public/logos/logo_placeholder.png", description="Icon URL"
    )
    author_name: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    sdk_example_path: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    locale: Optional[Annotated[str, Field(strict=True, max_length=8)]] = "en"
    __properties: ClassVar[List[str]] = [
        "slug",
        "title",
        "description",
        "content_markdown",
        "chains",
        "tokens",
        "tags",
        "category",
        "example_prompts",
        "icon",
        "author_name",
        "sdk_example_path",
        "locale",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecipeSubmissionCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecipeSubmissionCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "slug": obj.get("slug"),
                "title": obj.get("title"),
                "description": obj.get("description"),
                "content_markdown": obj.get("content_markdown")
                if obj.get("content_markdown") is not None
                else "",
                "chains": obj.get("chains"),
                "tokens": obj.get("tokens"),
                "tags": obj.get("tags"),
                "category": obj.get("category"),
                "example_prompts": obj.get("example_prompts"),
                "icon": obj.get("icon")
                if obj.get("icon") is not None
                else "https://d.cobo.com/public/logos/logo_placeholder.png",
                "author_name": obj.get("author_name"),
                "sdk_example_path": obj.get("sdk_example_path"),
                "locale": obj.get("locale") if obj.get("locale") is not None else "en",
            }
        )
        return _obj
