# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Set
from typing_extensions import Self


class SessionSpan(BaseModel):
    """
    A span within a CLI session representing a single unit of work, such as a generation step or a tool call.
    """  # noqa: E501

    name: Optional[StrictStr] = None
    record_type: Optional[StrictStr] = None
    start_time_unix_nano: Optional[StrictInt] = None
    end_time_unix_nano: Optional[StrictInt] = None
    duration_ms: Optional[Union[StrictFloat, StrictInt]] = None
    status_code: Optional[StrictStr] = None
    status_message: Optional[StrictStr] = None
    attributes: Optional[Dict[str, Any]] = None
    children: Optional[List[SessionSpan]] = None
    __properties: ClassVar[List[str]] = [
        "name",
        "record_type",
        "start_time_unix_nano",
        "end_time_unix_nano",
        "duration_ms",
        "status_code",
        "status_message",
        "attributes",
        "children",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SessionSpan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item in self.children:
                if _item:
                    _items.append(_item.to_dict())
            _dict["children"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SessionSpan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "record_type": obj.get("record_type"),
                "start_time_unix_nano": obj.get("start_time_unix_nano"),
                "end_time_unix_nano": obj.get("end_time_unix_nano"),
                "duration_ms": obj.get("duration_ms"),
                "status_code": obj.get("status_code"),
                "status_message": obj.get("status_message"),
                "attributes": obj.get("attributes"),
                "children": [SessionSpan.from_dict(_item) for _item in obj["children"]]
                if obj.get("children") is not None
                else None,
            }
        )
        return _obj


# TODO: Rewrite to not use raise_errors
SessionSpan.model_rebuild(raise_errors=False)
