# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.2.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_agentic_wallet_api.models.session_span import SessionSpan
from typing import Set
from typing_extensions import Self


class SessionRecord(BaseModel):
    """
    A session telemetry record containing nested turn and child spans.  Posted by otel_report.py to /api/v1/telemetry/session. Uses the Langfuse SDK directly (rather than OpenTelemetry) to preserve proper parent-child nesting.
    """  # noqa: E501

    name: Optional[StrictStr] = None
    trace_name: Optional[StrictStr] = None
    session_id: Optional[StrictStr] = None
    user_id: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    metadata: Optional[Dict[str, Any]] = None
    attributes: Optional[Dict[str, Any]] = None
    start_time_unix_nano: Optional[StrictInt] = None
    end_time_unix_nano: Optional[StrictInt] = None
    children: Optional[List[SessionSpan]] = None
    __properties: ClassVar[List[str]] = [
        "name",
        "trace_name",
        "session_id",
        "user_id",
        "tags",
        "metadata",
        "attributes",
        "start_time_unix_nano",
        "end_time_unix_nano",
        "children",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SessionRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item in self.children:
                if _item:
                    _items.append(_item.to_dict())
            _dict["children"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SessionRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "trace_name": obj.get("trace_name"),
                "session_id": obj.get("session_id"),
                "user_id": obj.get("user_id"),
                "tags": obj.get("tags"),
                "metadata": obj.get("metadata"),
                "attributes": obj.get("attributes"),
                "start_time_unix_nano": obj.get("start_time_unix_nano"),
                "end_time_unix_nano": obj.get("end_time_unix_nano"),
                "children": [SessionSpan.from_dict(_item) for _item in obj["children"]]
                if obj.get("children") is not None
                else None,
            }
        )
        return _obj
