# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class TokenMetadata(BaseModel):
    """
    Token and asset metadata returned by the Cobo WaaS API. Describes a supported token, including its chain, decimals, deposit/withdrawal eligibility, and fee token.
    """  # noqa: E501

    token_id: StrictStr
    chain_id: Optional[StrictStr] = ""
    asset_id: Optional[StrictStr] = ""
    symbol: Optional[StrictStr] = ""
    name: Optional[StrictStr] = ""
    decimal: Optional[StrictInt] = 0
    icon_url: Optional[StrictStr] = None
    token_address: Optional[StrictStr] = None
    fee_token_id: Optional[StrictStr] = ""
    can_deposit: Optional[StrictBool] = True
    can_withdraw: Optional[StrictBool] = True
    dust_threshold: Optional[StrictStr] = "0"
    custodial_minimum_deposit_threshold: Optional[StrictStr] = "0"
    asset_model_type: Optional[StrictStr] = ""
    __properties: ClassVar[List[str]] = [
        "token_id",
        "chain_id",
        "asset_id",
        "symbol",
        "name",
        "decimal",
        "icon_url",
        "token_address",
        "fee_token_id",
        "can_deposit",
        "can_withdraw",
        "dust_threshold",
        "custodial_minimum_deposit_threshold",
        "asset_model_type",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TokenMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TokenMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "token_id": obj.get("token_id"),
                "chain_id": obj.get("chain_id") if obj.get("chain_id") is not None else "",
                "asset_id": obj.get("asset_id") if obj.get("asset_id") is not None else "",
                "symbol": obj.get("symbol") if obj.get("symbol") is not None else "",
                "name": obj.get("name") if obj.get("name") is not None else "",
                "decimal": obj.get("decimal") if obj.get("decimal") is not None else 0,
                "icon_url": obj.get("icon_url"),
                "token_address": obj.get("token_address"),
                "fee_token_id": obj.get("fee_token_id")
                if obj.get("fee_token_id") is not None
                else "",
                "can_deposit": obj.get("can_deposit")
                if obj.get("can_deposit") is not None
                else True,
                "can_withdraw": obj.get("can_withdraw")
                if obj.get("can_withdraw") is not None
                else True,
                "dust_threshold": obj.get("dust_threshold")
                if obj.get("dust_threshold") is not None
                else "0",
                "custodial_minimum_deposit_threshold": obj.get(
                    "custodial_minimum_deposit_threshold"
                )
                if obj.get("custodial_minimum_deposit_threshold") is not None
                else "0",
                "asset_model_type": obj.get("asset_model_type")
                if obj.get("asset_model_type") is not None
                else "",
            }
        )
        return _obj
