# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_agentic_wallet_api.models.external_transaction_read import ExternalTransactionRead
from cobo_agentic_wallet_api.models.user_transaction_data import UserTransactionData
from cobo_agentic_wallet_api.models.user_transaction_operation_type import (
    UserTransactionOperationType,
)
from cobo_agentic_wallet_api.models.user_transaction_request_type import UserTransactionRequestType
from typing import Set
from typing_extensions import Self


class UserTransactionRead(BaseModel):
    """
    Public representation of a user transaction.
    """  # noqa: E501

    id: StrictStr = Field(description="The transaction record ID.")
    wallet_id: StrictStr = Field(description="The wallet ID this transaction belongs to.")
    pact_id: Optional[StrictStr] = Field(
        default=None,
        description="When the originating request used a pact-scoped API key, the pact UUID (mirrors `data.pact_id` when set).",
    )
    type: UserTransactionOperationType = Field(
        description="The operation type. Possible values: `transfer`, `contract_call`, `message_sign`, `deposit`."
    )
    request_type: Optional[UserTransactionRequestType] = Field(
        default=None,
        description="The originating request type. Possible values: `transfer`, `contract_call`, `deposit`, `message_sign`, `x402_payment`, `mpp_payment`. When multiple request_types share the same operation type (e.g. x402_payment → transfer), this field distinguishes the source.",
    )
    chain_id: StrictStr = Field(
        description="The Cobo chain ID for this transaction (for example, `SETH`, `BASE_ETH`, `SOL`)."
    )
    token_id: StrictStr = Field(
        description="The Cobo token ID for this transaction (for example, `SETH`, `SETH_USDC`)."
    )
    src_address: StrictStr = Field(description="The source on-chain address.")
    dst_address: StrictStr = Field(description="The destination on-chain address.")
    amount: StrictStr = Field(description="The transaction amount as a decimal string.")
    status: StrictInt = Field(description="The transaction status code.")
    status_display: Optional[StrictStr] = Field(
        default="",
        description="The human-readable transaction status (for example, `success`, `failed`, `broadcasting`).",
    )
    sub_status: Optional[StrictStr] = Field(
        default=None,
        description="The fine-grained transaction sub-status (for example, `broadcasting`, `pendingscreening`). Mirrors `UserTransaction.sub_status`.",
    )
    transaction_hash: Optional[str] = None
    request_id: Optional[StrictStr] = Field(
        default=None, description="The client-supplied request identifier, if set."
    )
    description: Optional[StrictStr] = Field(
        default=None,
        description="Optional note from submission; duplicated from `data.description` when present.",
    )
    data: UserTransactionData = Field(description="Additional transaction metadata.")
    created_at: datetime = Field(
        description="The timestamp when this record was created, in ISO 8601 format."
    )
    updated_at: datetime = Field(
        description="The timestamp when this record was last updated, in ISO 8601 format."
    )
    ext_transactions: Optional[List[ExternalTransactionRead]] = Field(
        default=None,
        description="Associated external (downstream) transactions. Only populated when the request includes `ext=true`.",
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "wallet_id",
        "pact_id",
        "type",
        "request_type",
        "chain_id",
        "token_id",
        "src_address",
        "dst_address",
        "amount",
        "status",
        "status_display",
        "sub_status",
        "transaction_hash",
        "request_id",
        "description",
        "data",
        "created_at",
        "updated_at",
        "ext_transactions",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserTransactionRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict["data"] = self.data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in ext_transactions (list)
        _items = []
        if self.ext_transactions:
            for _item in self.ext_transactions:
                if _item:
                    _items.append(_item.to_dict())
            _dict["ext_transactions"] = _items
        # set to None if transaction_hash (nullable) is None
        # and model_fields_set contains the field
        if self.transaction_hash is None and "transaction_hash" in self.model_fields_set:
            _dict["transaction_hash"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserTransactionRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "wallet_id": obj.get("wallet_id"),
                "pact_id": obj.get("pact_id"),
                "type": obj.get("type"),
                "request_type": obj.get("request_type"),
                "chain_id": obj.get("chain_id"),
                "token_id": obj.get("token_id"),
                "src_address": obj.get("src_address"),
                "dst_address": obj.get("dst_address"),
                "amount": obj.get("amount"),
                "status": obj.get("status"),
                "status_display": obj.get("status_display")
                if obj.get("status_display") is not None
                else "",
                "sub_status": obj.get("sub_status"),
                "transaction_hash": obj.get("transaction_hash"),
                "request_id": obj.get("request_id"),
                "description": obj.get("description"),
                "data": UserTransactionData.from_dict(obj["data"])
                if obj.get("data") is not None
                else None,
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "ext_transactions": [
                    ExternalTransactionRead.from_dict(_item) for _item in obj["ext_transactions"]
                ]
                if obj.get("ext_transactions") is not None
                else None,
            }
        )
        return _obj
