# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.2.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_agentic_wallet_api.models.wallet_pair_agent_info import WalletPairAgentInfo
from cobo_agentic_wallet_api.models.wallet_pair_status import WalletPairStatus
from cobo_agentic_wallet_api.models.wallet_pair_token_purpose import WalletPairTokenPurpose
from cobo_agentic_wallet_api.models.wallet_pair_wallet_info import WalletPairWalletInfo
from typing import Set
from typing_extensions import Self


class WalletPairInitiateRead(BaseModel):
    """
    Wallet pairing initiate response payload.
    """  # noqa: E501

    id: StrictStr = Field(description="The pairing record ID.")
    wallet_id: StrictStr = Field(description="The wallet being paired.")
    claimer_principal_id: Optional[str] = None
    agent_principal_id: StrictStr = Field(
        description="The ID of the agent principal that initiated pairing."
    )
    token: StrictStr = Field(description="The 8-digit numeric code used to authorize pairing.")
    status: WalletPairStatus = Field(
        description="The pairing status. Possible values: `pending`, `paired`, `completed`."
    )
    token_purpose: WalletPairTokenPurpose = Field(
        description="`pair` = initial claim flow; `restore` = post-completion recovery code."
    )
    expires_at: datetime = Field(
        description="The timestamp when the pairing token expires, in ISO 8601 format."
    )
    created_at: datetime = Field(
        description="The timestamp when the pairing record was created, in ISO 8601 format."
    )
    updated_at: datetime = Field(
        description="The timestamp when the pairing record was last updated, in ISO 8601 format."
    )
    agent: Optional[WalletPairAgentInfo] = Field(
        default=None,
        description="The agent principal that initiated pairing. Included on initiate and confirm responses.",
    )
    wallet: Optional[WalletPairWalletInfo] = Field(
        default=None,
        description="The wallet being paired. Included on initiate and confirm responses.",
    )
    pair_link: StrictStr = Field(
        description="Pair page link in the Cobo Agentic Wallet app, formatted as {WEB_CONSOLE_HOST}/wallet/pair?token=xxxx"
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "wallet_id",
        "claimer_principal_id",
        "agent_principal_id",
        "token",
        "status",
        "token_purpose",
        "expires_at",
        "created_at",
        "updated_at",
        "agent",
        "wallet",
        "pair_link",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WalletPairInitiateRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of agent
        if self.agent:
            _dict["agent"] = self.agent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of wallet
        if self.wallet:
            _dict["wallet"] = self.wallet.to_dict()
        # set to None if claimer_principal_id (nullable) is None
        # and model_fields_set contains the field
        if self.claimer_principal_id is None and "claimer_principal_id" in self.model_fields_set:
            _dict["claimer_principal_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WalletPairInitiateRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "wallet_id": obj.get("wallet_id"),
                "claimer_principal_id": obj.get("claimer_principal_id"),
                "agent_principal_id": obj.get("agent_principal_id"),
                "token": obj.get("token"),
                "status": obj.get("status"),
                "token_purpose": obj.get("token_purpose"),
                "expires_at": obj.get("expires_at"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "agent": WalletPairAgentInfo.from_dict(obj["agent"])
                if obj.get("agent") is not None
                else None,
                "wallet": WalletPairWalletInfo.from_dict(obj["wallet"])
                if obj.get("wallet") is not None
                else None,
                "pair_link": obj.get("pair_link"),
            }
        )
        return _obj
