# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class WalletAddressRead(BaseModel):
    """
    Wallet address response payload.
    """  # noqa: E501

    wallet_id: StrictStr = Field(description="The wallet ID.")
    chain_type: Optional[StrictStr] = Field(
        default="",
        description="The address standard shared across chains — chains with the same chain_type share one wallet address. E.g. ETH, BASE, ARB, OP, BSC, MATIC, AVAXC, and SETH are all chain_type: ETH, so they all use the same 0x... address.",
    )
    compatible_chains: Optional[List[StrictStr]] = Field(
        default=None,
        description="Supported chain IDs that share the same address under this chain_type.",
    )
    address: StrictStr = Field(description="The on-chain address.")
    created_at: datetime = Field(
        description="The timestamp when the address was created, in ISO 8601 format."
    )
    updated_at: datetime = Field(
        description="The timestamp when the address was last updated, in ISO 8601 format."
    )
    __properties: ClassVar[List[str]] = [
        "wallet_id",
        "chain_type",
        "compatible_chains",
        "address",
        "created_at",
        "updated_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WalletAddressRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WalletAddressRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "wallet_id": obj.get("wallet_id"),
                "chain_type": obj.get("chain_type") if obj.get("chain_type") is not None else "",
                "compatible_chains": obj.get("compatible_chains"),
                "address": obj.get("address"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
            }
        )
        return _obj
