# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class WalletAddressInfo(BaseModel):
    """
    A single wallet address with derivation info.
    """  # noqa: E501

    chain_id: StrictStr = Field(
        description="Identifier of the blockchain network this address belongs to (e.g. 'ETH', 'BTC')."
    )
    address: StrictStr = Field(
        description="Blockchain address string in the format native to the specified chain (e.g. '0x…' for EVM chains, 'bc1…' for Bitcoin bech32)."
    )
    path: Optional[StrictStr] = Field(
        default="",
        description="BIP-32 derivation path used to derive this address from the root key (e.g. 'm/44'/60'/0'/0/0'). Empty string if not applicable.",
    )
    pubkey: Optional[StrictStr] = Field(
        default="",
        description="Compressed public key corresponding to this address, hex-encoded. Empty string if not yet populated.",
    )
    encoding: Optional[StrictStr] = Field(
        default="",
        description="Address encoding format applied to the public key (e.g. 'bech32', 'base58'). Empty string if not applicable.",
    )
    root_pubkey: Optional[StrictStr] = Field(
        default="",
        description="Hex-encoded root public key from which this address is derived. Empty string if not yet populated.",
    )
    __properties: ClassVar[List[str]] = [
        "chain_id",
        "address",
        "path",
        "pubkey",
        "encoding",
        "root_pubkey",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WalletAddressInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WalletAddressInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "chain_id": obj.get("chain_id"),
                "address": obj.get("address"),
                "path": obj.get("path") if obj.get("path") is not None else "",
                "pubkey": obj.get("pubkey") if obj.get("pubkey") is not None else "",
                "encoding": obj.get("encoding") if obj.get("encoding") is not None else "",
                "root_pubkey": obj.get("root_pubkey") if obj.get("root_pubkey") is not None else "",
            }
        )
        return _obj
