# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class WebhookRegistrationRead(BaseModel):
    """
    Webhook registration response.
    """  # noqa: E501

    id: StrictStr = Field(description="Unique identifier of the webhook registration.")
    callback_url: StrictStr = Field(
        description="The HTTPS URL that receives webhook POST requests."
    )
    owner_id: Optional[StrictStr] = Field(
        default=None, description="UUID of the owner associated with this registration, if any."
    )
    event_types: Optional[List[StrictStr]] = Field(
        default=None, description="List of subscribed event type strings."
    )
    is_active: StrictBool = Field(
        description="Whether this webhook registration is currently active and will receive events."
    )
    created_at: datetime = Field(description="Timestamp when the webhook registration was created.")
    __properties: ClassVar[List[str]] = [
        "id",
        "callback_url",
        "owner_id",
        "event_types",
        "is_active",
        "created_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookRegistrationRead from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookRegistrationRead from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "callback_url": obj.get("callback_url"),
                "owner_id": obj.get("owner_id"),
                "event_types": obj.get("event_types"),
                "is_active": obj.get("is_active"),
                "created_at": obj.get("created_at"),
            }
        )
        return _obj
