# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import json
import ssl
from typing import Optional

from cobo_agentic_wallet_api.exceptions import ApiException, ApiValueError

try:
    import aiohttp

    HAS_AIOHTTP = True
except ImportError:
    HAS_AIOHTTP = False


class AsyncRESTResponse:
    """Async REST response wrapper."""

    def __init__(self, resp: "aiohttp.ClientResponse", data: bytes) -> None:
        self.response = resp
        self.status = resp.status
        self.reason = resp.reason
        self.data = data

    def getheaders(self):
        """Returns a dictionary of the response headers."""
        return dict(self.response.headers)

    def getheader(self, name, default=None):
        """Returns a given response header."""
        return self.response.headers.get(name, default)


class AsyncRESTClientObject:
    """Async REST client using aiohttp."""

    def __init__(self, configuration) -> None:
        if not HAS_AIOHTTP:
            raise ImportError(
                "aiohttp is required for async support. "
                "Install it with: pip install cobo-agentic-wallet[async]"
            )

        self.configuration = configuration
        self._session: Optional["aiohttp.ClientSession"] = None

        # SSL context
        if configuration.verify_ssl:
            self._ssl_context = ssl.create_default_context()
            if configuration.ssl_ca_cert:
                self._ssl_context.load_verify_locations(configuration.ssl_ca_cert)
            if configuration.cert_file:
                self._ssl_context.load_cert_chain(
                    configuration.cert_file, keyfile=configuration.key_file
                )
        else:
            self._ssl_context = False

    async def _get_session(self) -> "aiohttp.ClientSession":
        """Get or create aiohttp session."""
        if self._session is None or self._session.closed:
            connector_kwargs = {}
            if self.configuration.proxy:
                # aiohttp handles proxy differently
                pass
            timeout = aiohttp.ClientTimeout(
                total=self.configuration.request_timeout
                if hasattr(self.configuration, "request_timeout")
                else 300
            )
            self._session = aiohttp.ClientSession(
                timeout=timeout, connector=aiohttp.TCPConnector(ssl=self._ssl_context)
            )
        return self._session

    async def close(self):
        """Close the aiohttp session."""
        if self._session and not self._session.closed:
            await self._session.close()
            self._session = None

    async def request(
        self, method, url, headers=None, body=None, post_params=None, _request_timeout=None
    ) -> AsyncRESTResponse:
        """Perform async HTTP requests.

        :param method: http request method
        :param url: http request url
        :param headers: http request headers
        :param body: request json body, for `application/json`
        :param post_params: request post parameters,
                            `application/x-www-form-urlencoded`
                            and `multipart/form-data`
        :param _request_timeout: timeout setting for this request.
        """
        method = method.upper()
        assert method in ["GET", "HEAD", "DELETE", "POST", "PUT", "PATCH", "OPTIONS"]

        if post_params and body:
            raise ApiValueError("body parameter cannot be used with post_params parameter.")

        headers = headers or {}
        session = await self._get_session()

        # Handle timeout
        timeout = None
        if _request_timeout:
            if isinstance(_request_timeout, (int, float)):
                timeout = aiohttp.ClientTimeout(total=_request_timeout)
            elif isinstance(_request_timeout, tuple) and len(_request_timeout) == 2:
                timeout = aiohttp.ClientTimeout(
                    connect=_request_timeout[0], sock_read=_request_timeout[1]
                )

        # Handle proxy
        proxy = self.configuration.proxy if self.configuration.proxy else None

        try:
            if method in ["POST", "PUT", "PATCH", "OPTIONS", "DELETE"]:
                content_type = headers.get("Content-Type")
                if not content_type or "json" in content_type.lower():
                    request_body = None
                    if body is not None:
                        request_body = json.dumps(body)
                    async with session.request(
                        method,
                        url,
                        data=request_body,
                        headers=headers,
                        timeout=timeout,
                        proxy=proxy,
                        ssl=self._ssl_context,
                    ) as resp:
                        data = await resp.read()
                        return AsyncRESTResponse(resp, data)

                elif content_type == "application/x-www-form-urlencoded":
                    async with session.request(
                        method,
                        url,
                        data=post_params,
                        headers=headers,
                        timeout=timeout,
                        proxy=proxy,
                        ssl=self._ssl_context,
                    ) as resp:
                        data = await resp.read()
                        return AsyncRESTResponse(resp, data)

                elif content_type == "multipart/form-data":
                    del headers["Content-Type"]
                    form_data = aiohttp.FormData()
                    if post_params:
                        for key, value in post_params:
                            if isinstance(value, dict):
                                form_data.add_field(key, json.dumps(value))
                            else:
                                form_data.add_field(key, value)
                    async with session.request(
                        method,
                        url,
                        data=form_data,
                        headers=headers,
                        timeout=timeout,
                        proxy=proxy,
                        ssl=self._ssl_context,
                    ) as resp:
                        data = await resp.read()
                        return AsyncRESTResponse(resp, data)

                elif isinstance(body, (str, bytes)):
                    async with session.request(
                        method,
                        url,
                        data=body,
                        headers=headers,
                        timeout=timeout,
                        proxy=proxy,
                        ssl=self._ssl_context,
                    ) as resp:
                        data = await resp.read()
                        return AsyncRESTResponse(resp, data)

                elif headers.get("Content-Type") == "text/plain" and isinstance(body, bool):
                    request_body = "true" if body else "false"
                    async with session.request(
                        method,
                        url,
                        data=request_body,
                        headers=headers,
                        timeout=timeout,
                        proxy=proxy,
                        ssl=self._ssl_context,
                    ) as resp:
                        data = await resp.read()
                        return AsyncRESTResponse(resp, data)

                else:
                    msg = """Cannot prepare a request message for provided
                             arguments. Please check that your arguments match
                             declared content type."""
                    raise ApiException(status=0, reason=msg)
            else:
                # GET, HEAD
                async with session.request(
                    method,
                    url,
                    headers=headers,
                    timeout=timeout,
                    proxy=proxy,
                    ssl=self._ssl_context,
                ) as resp:
                    data = await resp.read()
                    return AsyncRESTResponse(resp, data)

        except aiohttp.ClientSSLError as e:
            msg = "\n".join([type(e).__name__, str(e)])
            raise ApiException(status=0, reason=msg)
