# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from pydantic import validate_call, Field, StrictFloat, StrictStr
from typing import Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from cobo_agentic_wallet_api.models.api_key_create import ApiKeyCreate
from cobo_agentic_wallet_api.models.principal_create import PrincipalCreate
from cobo_agentic_wallet_api.models.principal_type import PrincipalType
from cobo_agentic_wallet_api.models.principal_update import PrincipalUpdate
from cobo_agentic_wallet_api.models.provision_request import ProvisionRequest
from cobo_agentic_wallet_api.models.standard_response_agent_status_response import (
    StandardResponseAgentStatusResponse,
)
from cobo_agentic_wallet_api.models.standard_response_api_key_create_result_public import (
    StandardResponseApiKeyCreateResultPublic,
)
from cobo_agentic_wallet_api.models.standard_response_dict_str_bool import (
    StandardResponseDictStrBool,
)
from cobo_agentic_wallet_api.models.standard_response_list_api_key_public_read import (
    StandardResponseListApiKeyPublicRead,
)
from cobo_agentic_wallet_api.models.standard_response_list_principal_read import (
    StandardResponseListPrincipalRead,
)
from cobo_agentic_wallet_api.models.standard_response_principal_create_result import (
    StandardResponsePrincipalCreateResult,
)
from cobo_agentic_wallet_api.models.standard_response_principal_read import (
    StandardResponsePrincipalRead,
)
from cobo_agentic_wallet_api.models.standard_response_provision_response import (
    StandardResponseProvisionResponse,
)

from cobo_agentic_wallet_api.api_client import ApiClient, RequestSerialized
from cobo_agentic_wallet_api.api_response import ApiResponse
from cobo_agentic_wallet_api.rest import RESTResponseType


class IdentityApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client: ApiClient = None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    def create_api_key(
        self,
        api_key_create: ApiKeyCreate,
        x_api_key: Optional[StrictStr] = None,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseApiKeyCreateResultPublic:
        """Create API key

        This operation creates a new API key for a principal.  When authenticated with a principal API key, the new key is created for the authenticated principal. When authenticated with a service credential, `principal_id` is required.  Use `scopes` to restrict what the key can access. The default scope `[\"*\"]` grants full access. Individual scopes use the format `resource:action` where action is `read`, `write`, or `status`. For example: `[\"wallet:read\", \"wallet:write\"]`.  Supply `expires_at` to set an expiry time. If omitted, the key does not expire.  <Note>The raw API key value is only returned once in the response. Store it securely — it cannot be retrieved again.</Note>

        :param api_key_create: (required)
        :type api_key_create: ApiKeyCreate
        :param x_api_key:
        :type x_api_key: str
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._create_api_key_serialize(
            api_key_create=api_key_create,
            x_api_key=x_api_key,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponseApiKeyCreateResultPublic",
            "422": "WrappedValidationError",
            "200": "StandardResponseApiKeyCreateResultPublic",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def create_api_key_with_http_info(
        self,
        api_key_create: ApiKeyCreate,
        x_api_key: Optional[StrictStr] = None,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseApiKeyCreateResultPublic]:
        """Create API key

        This operation creates a new API key for a principal.  When authenticated with a principal API key, the new key is created for the authenticated principal. When authenticated with a service credential, `principal_id` is required.  Use `scopes` to restrict what the key can access. The default scope `[\"*\"]` grants full access. Individual scopes use the format `resource:action` where action is `read`, `write`, or `status`. For example: `[\"wallet:read\", \"wallet:write\"]`.  Supply `expires_at` to set an expiry time. If omitted, the key does not expire.  <Note>The raw API key value is only returned once in the response. Store it securely — it cannot be retrieved again.</Note>

        :param api_key_create: (required)
        :type api_key_create: ApiKeyCreate
        :param x_api_key:
        :type x_api_key: str
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._create_api_key_serialize(
            api_key_create=api_key_create,
            x_api_key=x_api_key,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponseApiKeyCreateResultPublic",
            "422": "WrappedValidationError",
            "200": "StandardResponseApiKeyCreateResultPublic",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def create_api_key_without_preload_content(
        self,
        api_key_create: ApiKeyCreate,
        x_api_key: Optional[StrictStr] = None,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> RESTResponseType:
        """Create API key

        This operation creates a new API key for a principal.  When authenticated with a principal API key, the new key is created for the authenticated principal. When authenticated with a service credential, `principal_id` is required.  Use `scopes` to restrict what the key can access. The default scope `[\"*\"]` grants full access. Individual scopes use the format `resource:action` where action is `read`, `write`, or `status`. For example: `[\"wallet:read\", \"wallet:write\"]`.  Supply `expires_at` to set an expiry time. If omitted, the key does not expire.  <Note>The raw API key value is only returned once in the response. Store it securely — it cannot be retrieved again.</Note>

        :param api_key_create: (required)
        :type api_key_create: ApiKeyCreate
        :param x_api_key:
        :type x_api_key: str
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._create_api_key_serialize(
            api_key_create=api_key_create,
            x_api_key=x_api_key,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponseApiKeyCreateResultPublic",
            "422": "WrappedValidationError",
            "200": "StandardResponseApiKeyCreateResultPublic",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _create_api_key_serialize(
        self,
        api_key_create,
        x_api_key,
        x_assistant_service_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params["X-API-Key"] = x_api_key
        if x_assistant_service_key is not None:
            _header_params["X-Assistant-Service-Key"] = x_assistant_service_key
        # process the form parameters
        # process the body parameter
        if api_key_create is not None:
            _body_params = api_key_create

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/v1/api-keys",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    def create_principal(
        self,
        principal_create: PrincipalCreate,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponsePrincipalCreateResult:
        """Create principal

        This operation creates a new principal (a human or agent identity). Requires service credential authentication via `X-Service-Auth-Key`. If a principal with the same `external_id` already exists, the existing record is returned with `created=false` and HTTP 200.

        :param principal_create: (required)
        :type principal_create: PrincipalCreate
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._create_principal_serialize(
            principal_create=principal_create,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponsePrincipalCreateResult",
            "422": "WrappedValidationError",
            "200": "StandardResponsePrincipalCreateResult",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def create_principal_with_http_info(
        self,
        principal_create: PrincipalCreate,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponsePrincipalCreateResult]:
        """Create principal

        This operation creates a new principal (a human or agent identity). Requires service credential authentication via `X-Service-Auth-Key`. If a principal with the same `external_id` already exists, the existing record is returned with `created=false` and HTTP 200.

        :param principal_create: (required)
        :type principal_create: PrincipalCreate
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._create_principal_serialize(
            principal_create=principal_create,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponsePrincipalCreateResult",
            "422": "WrappedValidationError",
            "200": "StandardResponsePrincipalCreateResult",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def create_principal_without_preload_content(
        self,
        principal_create: PrincipalCreate,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> RESTResponseType:
        """Create principal

        This operation creates a new principal (a human or agent identity). Requires service credential authentication via `X-Service-Auth-Key`. If a principal with the same `external_id` already exists, the existing record is returned with `created=false` and HTTP 200.

        :param principal_create: (required)
        :type principal_create: PrincipalCreate
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._create_principal_serialize(
            principal_create=principal_create,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponsePrincipalCreateResult",
            "422": "WrappedValidationError",
            "200": "StandardResponsePrincipalCreateResult",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _create_principal_serialize(
        self,
        principal_create,
        x_assistant_service_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_assistant_service_key is not None:
            _header_params["X-Assistant-Service-Key"] = x_assistant_service_key
        # process the form parameters
        # process the body parameter
        if principal_create is not None:
            _body_params = principal_create

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/v1/principals",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    def get_agent_status(
        self,
        agent_id: Annotated[
            StrictStr,
            Field(
                description="The agent's unique identifier. Accepts either the internal UUID (returned as `id` by the Provision agent operation) or the external ID (`external_id`)."
            ),
        ],
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseAgentStatusResponse:
        """Get agent status

        This operation retrieves the provisioning and activation status of a specific agent. The agent ID is returned as `agent_id` in the Provision agent response. Accepts either the internal UUID or the external ID. Requires authentication with the agent's own API key.

        :param agent_id: The agent's unique identifier. Accepts either the internal UUID (returned as `id` by the Provision agent operation) or the external ID (`external_id`). (required)
        :type agent_id: str
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_agent_status_serialize(
            agent_id=agent_id,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseAgentStatusResponse",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def get_agent_status_with_http_info(
        self,
        agent_id: Annotated[
            StrictStr,
            Field(
                description="The agent's unique identifier. Accepts either the internal UUID (returned as `id` by the Provision agent operation) or the external ID (`external_id`)."
            ),
        ],
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseAgentStatusResponse]:
        """Get agent status

        This operation retrieves the provisioning and activation status of a specific agent. The agent ID is returned as `agent_id` in the Provision agent response. Accepts either the internal UUID or the external ID. Requires authentication with the agent's own API key.

        :param agent_id: The agent's unique identifier. Accepts either the internal UUID (returned as `id` by the Provision agent operation) or the external ID (`external_id`). (required)
        :type agent_id: str
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_agent_status_serialize(
            agent_id=agent_id,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseAgentStatusResponse",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def get_agent_status_without_preload_content(
        self,
        agent_id: Annotated[
            StrictStr,
            Field(
                description="The agent's unique identifier. Accepts either the internal UUID (returned as `id` by the Provision agent operation) or the external ID (`external_id`)."
            ),
        ],
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> RESTResponseType:
        """Get agent status

        This operation retrieves the provisioning and activation status of a specific agent. The agent ID is returned as `agent_id` in the Provision agent response. Accepts either the internal UUID or the external ID. Requires authentication with the agent's own API key.

        :param agent_id: The agent's unique identifier. Accepts either the internal UUID (returned as `id` by the Provision agent operation) or the external ID (`external_id`). (required)
        :type agent_id: str
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_agent_status_serialize(
            agent_id=agent_id,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseAgentStatusResponse",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _get_agent_status_serialize(
        self,
        agent_id,
        x_api_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        if agent_id is not None:
            _path_params["agent_id"] = agent_id
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params["X-API-Key"] = x_api_key
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/principals/{agent_id}/status",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    def list_api_keys(
        self,
        after: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page."
            ),
        ] = None,
        before: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page."
            ),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Deprecated. Use `after`/`before` cursors instead."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=200, strict=True, ge=1)]],
            Field(description="The maximum number of items to return. Range: [1, 200]."),
        ] = None,
        x_api_key: Optional[StrictStr] = None,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseListApiKeyPublicRead:
        """List API keys

        This operation retrieves all API keys for the authenticated principal. Requires principal API key authentication. Use cursor-based pagination with `after`/`before`.

        :param after: A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page.
        :type after: str
        :param before: A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page.
        :type before: str
        :param offset: Deprecated. Use `after`/`before` cursors instead.
        :type offset: int
        :param limit: The maximum number of items to return. Range: [1, 200].
        :type limit: int
        :param x_api_key:
        :type x_api_key: str
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_api_keys_serialize(
            after=after,
            before=before,
            offset=offset,
            limit=limit,
            x_api_key=x_api_key,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListApiKeyPublicRead",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def list_api_keys_with_http_info(
        self,
        after: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page."
            ),
        ] = None,
        before: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page."
            ),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Deprecated. Use `after`/`before` cursors instead."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=200, strict=True, ge=1)]],
            Field(description="The maximum number of items to return. Range: [1, 200]."),
        ] = None,
        x_api_key: Optional[StrictStr] = None,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseListApiKeyPublicRead]:
        """List API keys

        This operation retrieves all API keys for the authenticated principal. Requires principal API key authentication. Use cursor-based pagination with `after`/`before`.

        :param after: A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page.
        :type after: str
        :param before: A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page.
        :type before: str
        :param offset: Deprecated. Use `after`/`before` cursors instead.
        :type offset: int
        :param limit: The maximum number of items to return. Range: [1, 200].
        :type limit: int
        :param x_api_key:
        :type x_api_key: str
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_api_keys_serialize(
            after=after,
            before=before,
            offset=offset,
            limit=limit,
            x_api_key=x_api_key,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListApiKeyPublicRead",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def list_api_keys_without_preload_content(
        self,
        after: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page."
            ),
        ] = None,
        before: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page."
            ),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Deprecated. Use `after`/`before` cursors instead."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=200, strict=True, ge=1)]],
            Field(description="The maximum number of items to return. Range: [1, 200]."),
        ] = None,
        x_api_key: Optional[StrictStr] = None,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> RESTResponseType:
        """List API keys

        This operation retrieves all API keys for the authenticated principal. Requires principal API key authentication. Use cursor-based pagination with `after`/`before`.

        :param after: A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page.
        :type after: str
        :param before: A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page.
        :type before: str
        :param offset: Deprecated. Use `after`/`before` cursors instead.
        :type offset: int
        :param limit: The maximum number of items to return. Range: [1, 200].
        :type limit: int
        :param x_api_key:
        :type x_api_key: str
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_api_keys_serialize(
            after=after,
            before=before,
            offset=offset,
            limit=limit,
            x_api_key=x_api_key,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListApiKeyPublicRead",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _list_api_keys_serialize(
        self,
        after,
        before,
        offset,
        limit,
        x_api_key,
        x_assistant_service_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        if after is not None:
            _query_params.append(("after", after))

        if before is not None:
            _query_params.append(("before", before))

        if offset is not None:
            _query_params.append(("offset", offset))

        if limit is not None:
            _query_params.append(("limit", limit))

        # process the header parameters
        if x_api_key is not None:
            _header_params["X-API-Key"] = x_api_key
        if x_assistant_service_key is not None:
            _header_params["X-Assistant-Service-Key"] = x_assistant_service_key
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/api-keys",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    def list_my_agents(
        self,
        after: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page."
            ),
        ] = None,
        before: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page."
            ),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Deprecated. Use `after`/`before` cursors instead."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=200, strict=True, ge=1)]],
            Field(description="The maximum number of items to return. Range: [1, 200]."),
        ] = None,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseListPrincipalRead:
        """List my agents

        This operation retrieves all agent principals owned by the authenticated principal. Use cursor-based pagination with `after`/`before`.

        :param after: A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page.
        :type after: str
        :param before: A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page.
        :type before: str
        :param offset: Deprecated. Use `after`/`before` cursors instead.
        :type offset: int
        :param limit: The maximum number of items to return. Range: [1, 200].
        :type limit: int
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_my_agents_serialize(
            after=after,
            before=before,
            offset=offset,
            limit=limit,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListPrincipalRead",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def list_my_agents_with_http_info(
        self,
        after: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page."
            ),
        ] = None,
        before: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page."
            ),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Deprecated. Use `after`/`before` cursors instead."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=200, strict=True, ge=1)]],
            Field(description="The maximum number of items to return. Range: [1, 200]."),
        ] = None,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseListPrincipalRead]:
        """List my agents

        This operation retrieves all agent principals owned by the authenticated principal. Use cursor-based pagination with `after`/`before`.

        :param after: A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page.
        :type after: str
        :param before: A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page.
        :type before: str
        :param offset: Deprecated. Use `after`/`before` cursors instead.
        :type offset: int
        :param limit: The maximum number of items to return. Range: [1, 200].
        :type limit: int
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_my_agents_serialize(
            after=after,
            before=before,
            offset=offset,
            limit=limit,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListPrincipalRead",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def list_my_agents_without_preload_content(
        self,
        after: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page."
            ),
        ] = None,
        before: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page."
            ),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Deprecated. Use `after`/`before` cursors instead."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=200, strict=True, ge=1)]],
            Field(description="The maximum number of items to return. Range: [1, 200]."),
        ] = None,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> RESTResponseType:
        """List my agents

        This operation retrieves all agent principals owned by the authenticated principal. Use cursor-based pagination with `after`/`before`.

        :param after: A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page.
        :type after: str
        :param before: A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page.
        :type before: str
        :param offset: Deprecated. Use `after`/`before` cursors instead.
        :type offset: int
        :param limit: The maximum number of items to return. Range: [1, 200].
        :type limit: int
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_my_agents_serialize(
            after=after,
            before=before,
            offset=offset,
            limit=limit,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListPrincipalRead",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _list_my_agents_serialize(
        self,
        after,
        before,
        offset,
        limit,
        x_api_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        if after is not None:
            _query_params.append(("after", after))

        if before is not None:
            _query_params.append(("before", before))

        if offset is not None:
            _query_params.append(("offset", offset))

        if limit is not None:
            _query_params.append(("limit", limit))

        # process the header parameters
        if x_api_key is not None:
            _header_params["X-API-Key"] = x_api_key
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/principals/agents",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    def list_principals(
        self,
        after: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page."
            ),
        ] = None,
        before: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page."
            ),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Deprecated. Use `after`/`before` cursors instead."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=200, strict=True, ge=1)]],
            Field(description="The maximum number of items to return. Range: [1, 200]."),
        ] = None,
        type: Annotated[
            Optional[PrincipalType],
            Field(
                description="Filter principals by type. Possible values: `human`, `agent`. If omitted, all types are returned."
            ),
        ] = None,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseListPrincipalRead:
        """List all principals

        This operation retrieves all principals in the system. Requires service credential authentication via `X-Service-Auth-Key`. You can filter by principal type and use cursor-based pagination with `after`/`before`.

        :param after: A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page.
        :type after: str
        :param before: A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page.
        :type before: str
        :param offset: Deprecated. Use `after`/`before` cursors instead.
        :type offset: int
        :param limit: The maximum number of items to return. Range: [1, 200].
        :type limit: int
        :param type: Filter principals by type. Possible values: `human`, `agent`. If omitted, all types are returned.
        :type type: PrincipalType
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_principals_serialize(
            after=after,
            before=before,
            offset=offset,
            limit=limit,
            type=type,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListPrincipalRead",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def list_principals_with_http_info(
        self,
        after: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page."
            ),
        ] = None,
        before: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page."
            ),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Deprecated. Use `after`/`before` cursors instead."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=200, strict=True, ge=1)]],
            Field(description="The maximum number of items to return. Range: [1, 200]."),
        ] = None,
        type: Annotated[
            Optional[PrincipalType],
            Field(
                description="Filter principals by type. Possible values: `human`, `agent`. If omitted, all types are returned."
            ),
        ] = None,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseListPrincipalRead]:
        """List all principals

        This operation retrieves all principals in the system. Requires service credential authentication via `X-Service-Auth-Key`. You can filter by principal type and use cursor-based pagination with `after`/`before`.

        :param after: A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page.
        :type after: str
        :param before: A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page.
        :type before: str
        :param offset: Deprecated. Use `after`/`before` cursors instead.
        :type offset: int
        :param limit: The maximum number of items to return. Range: [1, 200].
        :type limit: int
        :param type: Filter principals by type. Possible values: `human`, `agent`. If omitted, all types are returned.
        :type type: PrincipalType
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_principals_serialize(
            after=after,
            before=before,
            offset=offset,
            limit=limit,
            type=type,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListPrincipalRead",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def list_principals_without_preload_content(
        self,
        after: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page."
            ),
        ] = None,
        before: Annotated[
            Optional[StrictStr],
            Field(
                description="A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page."
            ),
        ] = None,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Deprecated. Use `after`/`before` cursors instead."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=200, strict=True, ge=1)]],
            Field(description="The maximum number of items to return. Range: [1, 200]."),
        ] = None,
        type: Annotated[
            Optional[PrincipalType],
            Field(
                description="Filter principals by type. Possible values: `human`, `agent`. If omitted, all types are returned."
            ),
        ] = None,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> RESTResponseType:
        """List all principals

        This operation retrieves all principals in the system. Requires service credential authentication via `X-Service-Auth-Key`. You can filter by principal type and use cursor-based pagination with `after`/`before`.

        :param after: A cursor for forward pagination. Pass the `after` value from a previous response to retrieve the next page.
        :type after: str
        :param before: A cursor for backward pagination. Pass the `before` value from a previous response to retrieve the preceding page.
        :type before: str
        :param offset: Deprecated. Use `after`/`before` cursors instead.
        :type offset: int
        :param limit: The maximum number of items to return. Range: [1, 200].
        :type limit: int
        :param type: Filter principals by type. Possible values: `human`, `agent`. If omitted, all types are returned.
        :type type: PrincipalType
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_principals_serialize(
            after=after,
            before=before,
            offset=offset,
            limit=limit,
            type=type,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListPrincipalRead",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _list_principals_serialize(
        self,
        after,
        before,
        offset,
        limit,
        type,
        x_assistant_service_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        if after is not None:
            _query_params.append(("after", after))

        if before is not None:
            _query_params.append(("before", before))

        if offset is not None:
            _query_params.append(("offset", offset))

        if limit is not None:
            _query_params.append(("limit", limit))

        if type is not None:
            _query_params.append(("type", type.value))

        # process the header parameters
        if x_assistant_service_key is not None:
            _header_params["X-Assistant-Service-Key"] = x_assistant_service_key
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/principals",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    def provision_agent(
        self,
        provision_request: ProvisionRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseProvisionResponse:
        """Provision agent

        This operation provisions an agent by creating an API key. In token-based flows it also binds the agent to an owner.  Supply `token` to use the pairing code from the Cobo Agentic Wallet app (token-based provisioning). If `token` is omitted, provisioning runs in agent-first mode and returns an active agent credential.

        :param provision_request: (required)
        :type provision_request: ProvisionRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._provision_agent_serialize(
            provision_request=provision_request,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponseProvisionResponse",
            "422": "WrappedValidationError",
            "200": "StandardResponseProvisionResponse",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def provision_agent_with_http_info(
        self,
        provision_request: ProvisionRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseProvisionResponse]:
        """Provision agent

        This operation provisions an agent by creating an API key. In token-based flows it also binds the agent to an owner.  Supply `token` to use the pairing code from the Cobo Agentic Wallet app (token-based provisioning). If `token` is omitted, provisioning runs in agent-first mode and returns an active agent credential.

        :param provision_request: (required)
        :type provision_request: ProvisionRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._provision_agent_serialize(
            provision_request=provision_request,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponseProvisionResponse",
            "422": "WrappedValidationError",
            "200": "StandardResponseProvisionResponse",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def provision_agent_without_preload_content(
        self,
        provision_request: ProvisionRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> RESTResponseType:
        """Provision agent

        This operation provisions an agent by creating an API key. In token-based flows it also binds the agent to an owner.  Supply `token` to use the pairing code from the Cobo Agentic Wallet app (token-based provisioning). If `token` is omitted, provisioning runs in agent-first mode and returns an active agent credential.

        :param provision_request: (required)
        :type provision_request: ProvisionRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._provision_agent_serialize(
            provision_request=provision_request,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponseProvisionResponse",
            "422": "WrappedValidationError",
            "200": "StandardResponseProvisionResponse",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _provision_agent_serialize(
        self,
        provision_request,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if provision_request is not None:
            _body_params = provision_request

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/v1/principals/provision",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    def revoke_api_key(
        self,
        api_key_id: Annotated[
            StrictStr,
            Field(
                description="The UUID of the API key to revoke. You can retrieve this value by calling the List API keys operation."
            ),
        ],
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseDictStrBool:
        """Revoke API key

        This operation permanently revokes a specific API key. The API key ID can be retrieved by calling the List API keys operation. Once revoked, the key cannot be used for authentication.  <Warning>This action cannot be undone.</Warning>

        :param api_key_id: The UUID of the API key to revoke. You can retrieve this value by calling the List API keys operation. (required)
        :type api_key_id: str
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._revoke_api_key_serialize(
            api_key_id=api_key_id,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseDictStrBool",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def revoke_api_key_with_http_info(
        self,
        api_key_id: Annotated[
            StrictStr,
            Field(
                description="The UUID of the API key to revoke. You can retrieve this value by calling the List API keys operation."
            ),
        ],
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseDictStrBool]:
        """Revoke API key

        This operation permanently revokes a specific API key. The API key ID can be retrieved by calling the List API keys operation. Once revoked, the key cannot be used for authentication.  <Warning>This action cannot be undone.</Warning>

        :param api_key_id: The UUID of the API key to revoke. You can retrieve this value by calling the List API keys operation. (required)
        :type api_key_id: str
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._revoke_api_key_serialize(
            api_key_id=api_key_id,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseDictStrBool",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def revoke_api_key_without_preload_content(
        self,
        api_key_id: Annotated[
            StrictStr,
            Field(
                description="The UUID of the API key to revoke. You can retrieve this value by calling the List API keys operation."
            ),
        ],
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> RESTResponseType:
        """Revoke API key

        This operation permanently revokes a specific API key. The API key ID can be retrieved by calling the List API keys operation. Once revoked, the key cannot be used for authentication.  <Warning>This action cannot be undone.</Warning>

        :param api_key_id: The UUID of the API key to revoke. You can retrieve this value by calling the List API keys operation. (required)
        :type api_key_id: str
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._revoke_api_key_serialize(
            api_key_id=api_key_id,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseDictStrBool",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _revoke_api_key_serialize(
        self,
        api_key_id,
        x_api_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        if api_key_id is not None:
            _path_params["api_key_id"] = api_key_id
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params["X-API-Key"] = x_api_key
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="DELETE",
            resource_path="/api/v1/api-keys/{api_key_id}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    def update_principal(
        self,
        principal_id: Annotated[
            StrictStr,
            Field(
                description="The UUID of the principal to update. You can retrieve this value from the List all principals or List my agents operations."
            ),
        ],
        principal_update: PrincipalUpdate,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponsePrincipalRead:
        """Update principal

        This operation updates the display name of a principal. A principal can update its own name, or a human principal can update the name of an agent it owns.

        :param principal_id: The UUID of the principal to update. You can retrieve this value from the List all principals or List my agents operations. (required)
        :type principal_id: str
        :param principal_update: (required)
        :type principal_update: PrincipalUpdate
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._update_principal_serialize(
            principal_id=principal_id,
            principal_update=principal_update,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponsePrincipalRead",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    def update_principal_with_http_info(
        self,
        principal_id: Annotated[
            StrictStr,
            Field(
                description="The UUID of the principal to update. You can retrieve this value from the List all principals or List my agents operations."
            ),
        ],
        principal_update: PrincipalUpdate,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponsePrincipalRead]:
        """Update principal

        This operation updates the display name of a principal. A principal can update its own name, or a human principal can update the name of an agent it owns.

        :param principal_id: The UUID of the principal to update. You can retrieve this value from the List all principals or List my agents operations. (required)
        :type principal_id: str
        :param principal_update: (required)
        :type principal_update: PrincipalUpdate
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._update_principal_serialize(
            principal_id=principal_id,
            principal_update=principal_update,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponsePrincipalRead",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    def update_principal_without_preload_content(
        self,
        principal_id: Annotated[
            StrictStr,
            Field(
                description="The UUID of the principal to update. You can retrieve this value from the List all principals or List my agents operations."
            ),
        ],
        principal_update: PrincipalUpdate,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> RESTResponseType:
        """Update principal

        This operation updates the display name of a principal. A principal can update its own name, or a human principal can update the name of an agent it owns.

        :param principal_id: The UUID of the principal to update. You can retrieve this value from the List all principals or List my agents operations. (required)
        :type principal_id: str
        :param principal_update: (required)
        :type principal_update: PrincipalUpdate
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._update_principal_serialize(
            principal_id=principal_id,
            principal_update=principal_update,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponsePrincipalRead",
            "422": "WrappedValidationError",
        }
        response_data = self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data.response

    def _update_principal_serialize(
        self,
        principal_id,
        principal_update,
        x_api_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        if principal_id is not None:
            _path_params["principal_id"] = principal_id
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params["X-API-Key"] = x_api_key
        # process the form parameters
        # process the body parameter
        if principal_update is not None:
            _body_params = principal_update

        return self.api_client.param_serialize(
            method="PATCH",
            resource_path="/api/v1/principals/{principal_id}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )
