# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 1.2.4
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from pydantic import validate_call, Field, StrictFloat, StrictStr
from typing import Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from cobo_agentic_wallet_api.models.search_recipes_request import SearchRecipesRequest
from cobo_agentic_wallet_api.models.standard_response_list_pact_template_read import (
    StandardResponseListPactTemplateRead,
)
from cobo_agentic_wallet_api.models.standard_response_recipe_search_response import (
    StandardResponseRecipeSearchResponse,
)

from cobo_agentic_wallet_api.api_client_async import AsyncApiClient, RequestSerialized
from cobo_agentic_wallet_api.api_response import ApiResponse
from cobo_agentic_wallet_api.rest_async import AsyncRESTResponse


class AsyncRecipesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client: AsyncApiClient = None) -> None:
        if api_client is None:
            api_client = AsyncApiClient.get_default()
        self.api_client = api_client

    @validate_call
    async def list_pact_templates(
        self,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Number of items to skip."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=100, strict=True, ge=1)]],
            Field(description="Maximum number of items to return."),
        ] = None,
        recipe_slug: Annotated[
            Optional[StrictStr], Field(description="Filter by exact recipe slug.")
        ] = None,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseListPactTemplateRead:
        """List pact templates

        List all pact templates. Optionally filter by recipe_slug. Requires service credential authentication.

        :param offset: Number of items to skip.
        :type offset: int
        :param limit: Maximum number of items to return.
        :type limit: int
        :param recipe_slug: Filter by exact recipe slug.
        :type recipe_slug: str
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_pact_templates_serialize(
            offset=offset,
            limit=limit,
            recipe_slug=recipe_slug,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListPactTemplateRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def list_pact_templates_with_http_info(
        self,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Number of items to skip."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=100, strict=True, ge=1)]],
            Field(description="Maximum number of items to return."),
        ] = None,
        recipe_slug: Annotated[
            Optional[StrictStr], Field(description="Filter by exact recipe slug.")
        ] = None,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseListPactTemplateRead]:
        """List pact templates

        List all pact templates. Optionally filter by recipe_slug. Requires service credential authentication.

        :param offset: Number of items to skip.
        :type offset: int
        :param limit: Maximum number of items to return.
        :type limit: int
        :param recipe_slug: Filter by exact recipe slug.
        :type recipe_slug: str
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_pact_templates_serialize(
            offset=offset,
            limit=limit,
            recipe_slug=recipe_slug,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListPactTemplateRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def list_pact_templates_without_preload_content(
        self,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Number of items to skip."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=100, strict=True, ge=1)]],
            Field(description="Maximum number of items to return."),
        ] = None,
        recipe_slug: Annotated[
            Optional[StrictStr], Field(description="Filter by exact recipe slug.")
        ] = None,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """List pact templates

        List all pact templates. Optionally filter by recipe_slug. Requires service credential authentication.

        :param offset: Number of items to skip.
        :type offset: int
        :param limit: Maximum number of items to return.
        :type limit: int
        :param recipe_slug: Filter by exact recipe slug.
        :type recipe_slug: str
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_pact_templates_serialize(
            offset=offset,
            limit=limit,
            recipe_slug=recipe_slug,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListPactTemplateRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _list_pact_templates_serialize(
        self,
        offset,
        limit,
        recipe_slug,
        x_assistant_service_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        if offset is not None:
            _query_params.append(("offset", offset))

        if limit is not None:
            _query_params.append(("limit", limit))

        if recipe_slug is not None:
            _query_params.append(("recipe_slug", recipe_slug))

        # process the header parameters
        if x_assistant_service_key is not None:
            _header_params["X-Assistant-Service-Key"] = x_assistant_service_key
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/recipes/pact-templates",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def search_recipes(
        self,
        search_recipes_request: SearchRecipesRequest,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseRecipeSearchResponse:
        """Search recipes

        Search the recipe library using natural language via the knowledge hub. Optionally filter results by `chain` or `token`.

        :param search_recipes_request: (required)
        :type search_recipes_request: SearchRecipesRequest
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._search_recipes_serialize(
            search_recipes_request=search_recipes_request,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeSearchResponse",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def search_recipes_with_http_info(
        self,
        search_recipes_request: SearchRecipesRequest,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseRecipeSearchResponse]:
        """Search recipes

        Search the recipe library using natural language via the knowledge hub. Optionally filter results by `chain` or `token`.

        :param search_recipes_request: (required)
        :type search_recipes_request: SearchRecipesRequest
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._search_recipes_serialize(
            search_recipes_request=search_recipes_request,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeSearchResponse",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def search_recipes_without_preload_content(
        self,
        search_recipes_request: SearchRecipesRequest,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Search recipes

        Search the recipe library using natural language via the knowledge hub. Optionally filter results by `chain` or `token`.

        :param search_recipes_request: (required)
        :type search_recipes_request: SearchRecipesRequest
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._search_recipes_serialize(
            search_recipes_request=search_recipes_request,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeSearchResponse",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _search_recipes_serialize(
        self,
        search_recipes_request,
        x_api_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params["X-API-Key"] = x_api_key
        # process the form parameters
        # process the body parameter
        if search_recipes_request is not None:
            _body_params = search_recipes_request

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/v1/recipes/search",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )
