# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from pydantic import validate_call, Field, StrictFloat, StrictStr
from typing import Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import StrictBool
from cobo_agentic_wallet_api.models.recipe_create import RecipeCreate
from cobo_agentic_wallet_api.models.recipe_library_sort_by import RecipeLibrarySortBy
from cobo_agentic_wallet_api.models.recipe_review_request import RecipeReviewRequest
from cobo_agentic_wallet_api.models.recipe_search_source import RecipeSearchSource
from cobo_agentic_wallet_api.models.recipe_submission_create import RecipeSubmissionCreate
from cobo_agentic_wallet_api.models.recipe_update import RecipeUpdate
from cobo_agentic_wallet_api.models.search_recipes_request import SearchRecipesRequest
from cobo_agentic_wallet_api.models.standard_response_list_recipe_category_read import (
    StandardResponseListRecipeCategoryRead,
)
from cobo_agentic_wallet_api.models.standard_response_list_recipe_read import (
    StandardResponseListRecipeRead,
)
from cobo_agentic_wallet_api.models.standard_response_recipe_counter_result import (
    StandardResponseRecipeCounterResult,
)
from cobo_agentic_wallet_api.models.standard_response_recipe_create_result import (
    StandardResponseRecipeCreateResult,
)
from cobo_agentic_wallet_api.models.standard_response_recipe_detail_read import (
    StandardResponseRecipeDetailRead,
)
from cobo_agentic_wallet_api.models.standard_response_recipe_document import (
    StandardResponseRecipeDocument,
)
from cobo_agentic_wallet_api.models.standard_response_recipe_search_response import (
    StandardResponseRecipeSearchResponse,
)

from cobo_agentic_wallet_api.api_client_async import AsyncApiClient, RequestSerialized
from cobo_agentic_wallet_api.api_response import ApiResponse
from cobo_agentic_wallet_api.rest_async import AsyncRESTResponse


class AsyncRecipesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client: AsyncApiClient = None) -> None:
        if api_client is None:
            api_client = AsyncApiClient.get_default()
        self.api_client = api_client

    @validate_call
    async def archive_recipe(
        self,
        recipe_id: StrictStr,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseRecipeDetailRead:
        """Archive recipe

        Archive a recipe, removing it from public visibility. Requires service credential authentication. Archived recipes are not deleted and can be restored.

        :param recipe_id: (required)
        :type recipe_id: str
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._archive_recipe_serialize(
            recipe_id=recipe_id,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDetailRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def archive_recipe_with_http_info(
        self,
        recipe_id: StrictStr,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseRecipeDetailRead]:
        """Archive recipe

        Archive a recipe, removing it from public visibility. Requires service credential authentication. Archived recipes are not deleted and can be restored.

        :param recipe_id: (required)
        :type recipe_id: str
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._archive_recipe_serialize(
            recipe_id=recipe_id,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDetailRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def archive_recipe_without_preload_content(
        self,
        recipe_id: StrictStr,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Archive recipe

        Archive a recipe, removing it from public visibility. Requires service credential authentication. Archived recipes are not deleted and can be restored.

        :param recipe_id: (required)
        :type recipe_id: str
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._archive_recipe_serialize(
            recipe_id=recipe_id,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDetailRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _archive_recipe_serialize(
        self,
        recipe_id,
        x_assistant_service_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        if recipe_id is not None:
            _path_params["recipe_id"] = recipe_id
        # process the query parameters
        # process the header parameters
        if x_assistant_service_key is not None:
            _header_params["X-Assistant-Service-Key"] = x_assistant_service_key
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="DELETE",
            resource_path="/api/v1/recipes/library/{recipe_id}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def create_recipe(
        self,
        recipe_create: RecipeCreate,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseRecipeCreateResult:
        """Create recipe

        Create and publish a new recipe in the library. Requires service credential authentication. The recipe is synced to the knowledge hub after creation.

        :param recipe_create: (required)
        :type recipe_create: RecipeCreate
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._create_recipe_serialize(
            recipe_create=recipe_create,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponseRecipeCreateResult",
            "422": "WrappedValidationError",
            "200": "StandardResponseRecipeCreateResult",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def create_recipe_with_http_info(
        self,
        recipe_create: RecipeCreate,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseRecipeCreateResult]:
        """Create recipe

        Create and publish a new recipe in the library. Requires service credential authentication. The recipe is synced to the knowledge hub after creation.

        :param recipe_create: (required)
        :type recipe_create: RecipeCreate
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._create_recipe_serialize(
            recipe_create=recipe_create,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponseRecipeCreateResult",
            "422": "WrappedValidationError",
            "200": "StandardResponseRecipeCreateResult",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def create_recipe_without_preload_content(
        self,
        recipe_create: RecipeCreate,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Create recipe

        Create and publish a new recipe in the library. Requires service credential authentication. The recipe is synced to the knowledge hub after creation.

        :param recipe_create: (required)
        :type recipe_create: RecipeCreate
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._create_recipe_serialize(
            recipe_create=recipe_create,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponseRecipeCreateResult",
            "422": "WrappedValidationError",
            "200": "StandardResponseRecipeCreateResult",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _create_recipe_serialize(
        self,
        recipe_create,
        x_assistant_service_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_assistant_service_key is not None:
            _header_params["X-Assistant-Service-Key"] = x_assistant_service_key
        # process the form parameters
        # process the body parameter
        if recipe_create is not None:
            _body_params = recipe_create

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/v1/recipes/library",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def get_recipe_by_slug(
        self,
        slug: StrictStr,
        track_view: Annotated[
            Optional[StrictBool],
            Field(description="When `true` (default), increment the recipe's view counter."),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseRecipeDetailRead:
        """Get recipe detail by slug

        Retrieve the full details of a public recipe by its URL slug.

        :param slug: (required)
        :type slug: str
        :param track_view: When `true` (default), increment the recipe's view counter.
        :type track_view: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_recipe_by_slug_serialize(
            slug=slug,
            track_view=track_view,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDetailRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def get_recipe_by_slug_with_http_info(
        self,
        slug: StrictStr,
        track_view: Annotated[
            Optional[StrictBool],
            Field(description="When `true` (default), increment the recipe's view counter."),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseRecipeDetailRead]:
        """Get recipe detail by slug

        Retrieve the full details of a public recipe by its URL slug.

        :param slug: (required)
        :type slug: str
        :param track_view: When `true` (default), increment the recipe's view counter.
        :type track_view: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_recipe_by_slug_serialize(
            slug=slug,
            track_view=track_view,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDetailRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def get_recipe_by_slug_without_preload_content(
        self,
        slug: StrictStr,
        track_view: Annotated[
            Optional[StrictBool],
            Field(description="When `true` (default), increment the recipe's view counter."),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Get recipe detail by slug

        Retrieve the full details of a public recipe by its URL slug.

        :param slug: (required)
        :type slug: str
        :param track_view: When `true` (default), increment the recipe's view counter.
        :type track_view: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_recipe_by_slug_serialize(
            slug=slug,
            track_view=track_view,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDetailRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _get_recipe_by_slug_serialize(
        self,
        slug,
        track_view,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        if slug is not None:
            _path_params["slug"] = slug
        # process the query parameters
        if track_view is not None:
            _query_params.append(("track_view", track_view))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/recipes/library/by-slug/{slug}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def get_recipe_document(
        self,
        document_id: StrictStr,
        source: Annotated[
            Optional[RecipeSearchSource],
            Field(
                description="Document source to retrieve from. Possible values: `graph`, `knowledge`."
            ),
        ] = None,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseRecipeDocument:
        """Get full recipe document by ID

        Retrieve the full content of a recipe document by its knowledge hub or graph document ID. The `document_id` is returned in search results.

        :param document_id: (required)
        :type document_id: str
        :param source: Document source to retrieve from. Possible values: `graph`, `knowledge`.
        :type source: RecipeSearchSource
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_recipe_document_serialize(
            document_id=document_id,
            source=source,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDocument",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def get_recipe_document_with_http_info(
        self,
        document_id: StrictStr,
        source: Annotated[
            Optional[RecipeSearchSource],
            Field(
                description="Document source to retrieve from. Possible values: `graph`, `knowledge`."
            ),
        ] = None,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseRecipeDocument]:
        """Get full recipe document by ID

        Retrieve the full content of a recipe document by its knowledge hub or graph document ID. The `document_id` is returned in search results.

        :param document_id: (required)
        :type document_id: str
        :param source: Document source to retrieve from. Possible values: `graph`, `knowledge`.
        :type source: RecipeSearchSource
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_recipe_document_serialize(
            document_id=document_id,
            source=source,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDocument",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def get_recipe_document_without_preload_content(
        self,
        document_id: StrictStr,
        source: Annotated[
            Optional[RecipeSearchSource],
            Field(
                description="Document source to retrieve from. Possible values: `graph`, `knowledge`."
            ),
        ] = None,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Get full recipe document by ID

        Retrieve the full content of a recipe document by its knowledge hub or graph document ID. The `document_id` is returned in search results.

        :param document_id: (required)
        :type document_id: str
        :param source: Document source to retrieve from. Possible values: `graph`, `knowledge`.
        :type source: RecipeSearchSource
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_recipe_document_serialize(
            document_id=document_id,
            source=source,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDocument",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _get_recipe_document_serialize(
        self,
        document_id,
        source,
        x_api_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        if document_id is not None:
            _path_params["document_id"] = document_id
        # process the query parameters
        if source is not None:
            _query_params.append(("source", source.value))

        # process the header parameters
        if x_api_key is not None:
            _header_params["X-API-Key"] = x_api_key
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/recipes/{document_id}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def get_recipe_search_count(
        self,
        recipe_id: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseRecipeCounterResult:
        """Get recipe search count

        Retrieve the total number of times a recipe has appeared in search results.

        :param recipe_id: (required)
        :type recipe_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_recipe_search_count_serialize(
            recipe_id=recipe_id,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeCounterResult",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def get_recipe_search_count_with_http_info(
        self,
        recipe_id: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseRecipeCounterResult]:
        """Get recipe search count

        Retrieve the total number of times a recipe has appeared in search results.

        :param recipe_id: (required)
        :type recipe_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_recipe_search_count_serialize(
            recipe_id=recipe_id,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeCounterResult",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def get_recipe_search_count_without_preload_content(
        self,
        recipe_id: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Get recipe search count

        Retrieve the total number of times a recipe has appeared in search results.

        :param recipe_id: (required)
        :type recipe_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_recipe_search_count_serialize(
            recipe_id=recipe_id,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeCounterResult",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _get_recipe_search_count_serialize(
        self,
        recipe_id,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        if recipe_id is not None:
            _path_params["recipe_id"] = recipe_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/recipes/library/{recipe_id}/search-count",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def list_featured_recipes(
        self,
        limit: Annotated[
            Optional[Annotated[int, Field(le=50, strict=True, ge=1)]],
            Field(description="The maximum number of featured recipes to return. Range: [1, 50]."),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseListRecipeRead:
        """List featured recipes

        Retrieve the list of editorially featured recipes from the public library.

        :param limit: The maximum number of featured recipes to return. Range: [1, 50].
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_featured_recipes_serialize(
            limit=limit,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListRecipeRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def list_featured_recipes_with_http_info(
        self,
        limit: Annotated[
            Optional[Annotated[int, Field(le=50, strict=True, ge=1)]],
            Field(description="The maximum number of featured recipes to return. Range: [1, 50]."),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseListRecipeRead]:
        """List featured recipes

        Retrieve the list of editorially featured recipes from the public library.

        :param limit: The maximum number of featured recipes to return. Range: [1, 50].
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_featured_recipes_serialize(
            limit=limit,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListRecipeRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def list_featured_recipes_without_preload_content(
        self,
        limit: Annotated[
            Optional[Annotated[int, Field(le=50, strict=True, ge=1)]],
            Field(description="The maximum number of featured recipes to return. Range: [1, 50]."),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """List featured recipes

        Retrieve the list of editorially featured recipes from the public library.

        :param limit: The maximum number of featured recipes to return. Range: [1, 50].
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_featured_recipes_serialize(
            limit=limit,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListRecipeRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _list_featured_recipes_serialize(
        self,
        limit,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        if limit is not None:
            _query_params.append(("limit", limit))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/recipes/library/featured",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def list_recipe_categories(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseListRecipeCategoryRead:
        """List recipe categories

        Retrieve all available recipe categories from the public library.

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_recipe_categories_serialize()

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListRecipeCategoryRead",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def list_recipe_categories_with_http_info(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseListRecipeCategoryRead]:
        """List recipe categories

        Retrieve all available recipe categories from the public library.

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_recipe_categories_serialize()

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListRecipeCategoryRead",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def list_recipe_categories_without_preload_content(
        self,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """List recipe categories

        Retrieve all available recipe categories from the public library.

        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_recipe_categories_serialize()

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListRecipeCategoryRead",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _list_recipe_categories_serialize(
        self,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/recipes/library/categories",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def list_recipe_library(
        self,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Number of items to skip before returning results."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=100, strict=True, ge=1)]],
            Field(description="The maximum number of items to return. Range: [1, 100]."),
        ] = None,
        category: Annotated[
            Optional[StrictStr], Field(description="Filter recipes by category slug.")
        ] = None,
        tag: Annotated[Optional[StrictStr], Field(description="Filter recipes by tag.")] = None,
        chain: Annotated[
            Optional[StrictStr],
            Field(description="Filter recipes by blockchain (e.g. `ETH`, `SOL`)."),
        ] = None,
        featured: Annotated[
            Optional[StrictBool],
            Field(
                description="When `true`, return only featured recipes. When `false`, exclude featured recipes. Omit to return all."
            ),
        ] = None,
        query: Annotated[
            Optional[StrictStr],
            Field(description="Keyword search string to filter recipes by title or description."),
        ] = None,
        sort_by: Annotated[
            Optional[RecipeLibrarySortBy],
            Field(
                description="Sort order for results. Possible values: `popular`, `newest`, `most_used`."
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseListRecipeRead:
        """List recipes in the public library

        Retrieve published recipes from the public recipe library. Filter by category, tag, chain, or keyword. Use `offset` and `limit` for pagination.

        :param offset: Number of items to skip before returning results.
        :type offset: int
        :param limit: The maximum number of items to return. Range: [1, 100].
        :type limit: int
        :param category: Filter recipes by category slug.
        :type category: str
        :param tag: Filter recipes by tag.
        :type tag: str
        :param chain: Filter recipes by blockchain (e.g. `ETH`, `SOL`).
        :type chain: str
        :param featured: When `true`, return only featured recipes. When `false`, exclude featured recipes. Omit to return all.
        :type featured: bool
        :param query: Keyword search string to filter recipes by title or description.
        :type query: str
        :param sort_by: Sort order for results. Possible values: `popular`, `newest`, `most_used`.
        :type sort_by: RecipeLibrarySortBy
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_recipe_library_serialize(
            offset=offset,
            limit=limit,
            category=category,
            tag=tag,
            chain=chain,
            featured=featured,
            query=query,
            sort_by=sort_by,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListRecipeRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def list_recipe_library_with_http_info(
        self,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Number of items to skip before returning results."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=100, strict=True, ge=1)]],
            Field(description="The maximum number of items to return. Range: [1, 100]."),
        ] = None,
        category: Annotated[
            Optional[StrictStr], Field(description="Filter recipes by category slug.")
        ] = None,
        tag: Annotated[Optional[StrictStr], Field(description="Filter recipes by tag.")] = None,
        chain: Annotated[
            Optional[StrictStr],
            Field(description="Filter recipes by blockchain (e.g. `ETH`, `SOL`)."),
        ] = None,
        featured: Annotated[
            Optional[StrictBool],
            Field(
                description="When `true`, return only featured recipes. When `false`, exclude featured recipes. Omit to return all."
            ),
        ] = None,
        query: Annotated[
            Optional[StrictStr],
            Field(description="Keyword search string to filter recipes by title or description."),
        ] = None,
        sort_by: Annotated[
            Optional[RecipeLibrarySortBy],
            Field(
                description="Sort order for results. Possible values: `popular`, `newest`, `most_used`."
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseListRecipeRead]:
        """List recipes in the public library

        Retrieve published recipes from the public recipe library. Filter by category, tag, chain, or keyword. Use `offset` and `limit` for pagination.

        :param offset: Number of items to skip before returning results.
        :type offset: int
        :param limit: The maximum number of items to return. Range: [1, 100].
        :type limit: int
        :param category: Filter recipes by category slug.
        :type category: str
        :param tag: Filter recipes by tag.
        :type tag: str
        :param chain: Filter recipes by blockchain (e.g. `ETH`, `SOL`).
        :type chain: str
        :param featured: When `true`, return only featured recipes. When `false`, exclude featured recipes. Omit to return all.
        :type featured: bool
        :param query: Keyword search string to filter recipes by title or description.
        :type query: str
        :param sort_by: Sort order for results. Possible values: `popular`, `newest`, `most_used`.
        :type sort_by: RecipeLibrarySortBy
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_recipe_library_serialize(
            offset=offset,
            limit=limit,
            category=category,
            tag=tag,
            chain=chain,
            featured=featured,
            query=query,
            sort_by=sort_by,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListRecipeRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def list_recipe_library_without_preload_content(
        self,
        offset: Annotated[
            Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=0)]],
            Field(description="Number of items to skip before returning results."),
        ] = None,
        limit: Annotated[
            Optional[Annotated[int, Field(le=100, strict=True, ge=1)]],
            Field(description="The maximum number of items to return. Range: [1, 100]."),
        ] = None,
        category: Annotated[
            Optional[StrictStr], Field(description="Filter recipes by category slug.")
        ] = None,
        tag: Annotated[Optional[StrictStr], Field(description="Filter recipes by tag.")] = None,
        chain: Annotated[
            Optional[StrictStr],
            Field(description="Filter recipes by blockchain (e.g. `ETH`, `SOL`)."),
        ] = None,
        featured: Annotated[
            Optional[StrictBool],
            Field(
                description="When `true`, return only featured recipes. When `false`, exclude featured recipes. Omit to return all."
            ),
        ] = None,
        query: Annotated[
            Optional[StrictStr],
            Field(description="Keyword search string to filter recipes by title or description."),
        ] = None,
        sort_by: Annotated[
            Optional[RecipeLibrarySortBy],
            Field(
                description="Sort order for results. Possible values: `popular`, `newest`, `most_used`."
            ),
        ] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """List recipes in the public library

        Retrieve published recipes from the public recipe library. Filter by category, tag, chain, or keyword. Use `offset` and `limit` for pagination.

        :param offset: Number of items to skip before returning results.
        :type offset: int
        :param limit: The maximum number of items to return. Range: [1, 100].
        :type limit: int
        :param category: Filter recipes by category slug.
        :type category: str
        :param tag: Filter recipes by tag.
        :type tag: str
        :param chain: Filter recipes by blockchain (e.g. `ETH`, `SOL`).
        :type chain: str
        :param featured: When `true`, return only featured recipes. When `false`, exclude featured recipes. Omit to return all.
        :type featured: bool
        :param query: Keyword search string to filter recipes by title or description.
        :type query: str
        :param sort_by: Sort order for results. Possible values: `popular`, `newest`, `most_used`.
        :type sort_by: RecipeLibrarySortBy
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_recipe_library_serialize(
            offset=offset,
            limit=limit,
            category=category,
            tag=tag,
            chain=chain,
            featured=featured,
            query=query,
            sort_by=sort_by,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListRecipeRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _list_recipe_library_serialize(
        self,
        offset,
        limit,
        category,
        tag,
        chain,
        featured,
        query,
        sort_by,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        if offset is not None:
            _query_params.append(("offset", offset))

        if limit is not None:
            _query_params.append(("limit", limit))

        if category is not None:
            _query_params.append(("category", category))

        if tag is not None:
            _query_params.append(("tag", tag))

        if chain is not None:
            _query_params.append(("chain", chain))

        if featured is not None:
            _query_params.append(("featured", featured))

        if query is not None:
            _query_params.append(("query", query))

        if sort_by is not None:
            _query_params.append(("sort_by", sort_by.value))

        # process the header parameters
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/recipes/library",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def review_recipe_submission(
        self,
        recipe_id: StrictStr,
        recipe_review_request: RecipeReviewRequest,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseRecipeDetailRead:
        """Review submitted recipe

        Approve or reject a community-submitted recipe. Requires service credential authentication. Approved recipes are published to the library and synced to the knowledge hub.

        :param recipe_id: (required)
        :type recipe_id: str
        :param recipe_review_request: (required)
        :type recipe_review_request: RecipeReviewRequest
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._review_recipe_submission_serialize(
            recipe_id=recipe_id,
            recipe_review_request=recipe_review_request,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDetailRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def review_recipe_submission_with_http_info(
        self,
        recipe_id: StrictStr,
        recipe_review_request: RecipeReviewRequest,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseRecipeDetailRead]:
        """Review submitted recipe

        Approve or reject a community-submitted recipe. Requires service credential authentication. Approved recipes are published to the library and synced to the knowledge hub.

        :param recipe_id: (required)
        :type recipe_id: str
        :param recipe_review_request: (required)
        :type recipe_review_request: RecipeReviewRequest
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._review_recipe_submission_serialize(
            recipe_id=recipe_id,
            recipe_review_request=recipe_review_request,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDetailRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def review_recipe_submission_without_preload_content(
        self,
        recipe_id: StrictStr,
        recipe_review_request: RecipeReviewRequest,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Review submitted recipe

        Approve or reject a community-submitted recipe. Requires service credential authentication. Approved recipes are published to the library and synced to the knowledge hub.

        :param recipe_id: (required)
        :type recipe_id: str
        :param recipe_review_request: (required)
        :type recipe_review_request: RecipeReviewRequest
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._review_recipe_submission_serialize(
            recipe_id=recipe_id,
            recipe_review_request=recipe_review_request,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDetailRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _review_recipe_submission_serialize(
        self,
        recipe_id,
        recipe_review_request,
        x_assistant_service_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        if recipe_id is not None:
            _path_params["recipe_id"] = recipe_id
        # process the query parameters
        # process the header parameters
        if x_assistant_service_key is not None:
            _header_params["X-Assistant-Service-Key"] = x_assistant_service_key
        # process the form parameters
        # process the body parameter
        if recipe_review_request is not None:
            _body_params = recipe_review_request

        return self.api_client.param_serialize(
            method="PATCH",
            resource_path="/api/v1/recipes/library/submissions/{recipe_id}/review",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def search_recipes(
        self,
        search_recipes_request: SearchRecipesRequest,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseRecipeSearchResponse:
        """Search recipes

        Search the recipe library using natural language. Set `source` to `knowledge` (default) to query the knowledge hub, or `graph` to query the LightRAG graph index. Optionally filter results by `chain` or `token`.

        :param search_recipes_request: (required)
        :type search_recipes_request: SearchRecipesRequest
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._search_recipes_serialize(
            search_recipes_request=search_recipes_request,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeSearchResponse",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def search_recipes_with_http_info(
        self,
        search_recipes_request: SearchRecipesRequest,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseRecipeSearchResponse]:
        """Search recipes

        Search the recipe library using natural language. Set `source` to `knowledge` (default) to query the knowledge hub, or `graph` to query the LightRAG graph index. Optionally filter results by `chain` or `token`.

        :param search_recipes_request: (required)
        :type search_recipes_request: SearchRecipesRequest
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._search_recipes_serialize(
            search_recipes_request=search_recipes_request,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeSearchResponse",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def search_recipes_without_preload_content(
        self,
        search_recipes_request: SearchRecipesRequest,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Search recipes

        Search the recipe library using natural language. Set `source` to `knowledge` (default) to query the knowledge hub, or `graph` to query the LightRAG graph index. Optionally filter results by `chain` or `token`.

        :param search_recipes_request: (required)
        :type search_recipes_request: SearchRecipesRequest
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._search_recipes_serialize(
            search_recipes_request=search_recipes_request,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeSearchResponse",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _search_recipes_serialize(
        self,
        search_recipes_request,
        x_api_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params["X-API-Key"] = x_api_key
        # process the form parameters
        # process the body parameter
        if search_recipes_request is not None:
            _body_params = search_recipes_request

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/v1/recipes/search",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def submit_recipe(
        self,
        recipe_submission_create: RecipeSubmissionCreate,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseRecipeCreateResult:
        """Submit community recipe

        Submit a community-contributed recipe for review. The recipe enters a pending state until reviewed and approved by an admin.

        :param recipe_submission_create: (required)
        :type recipe_submission_create: RecipeSubmissionCreate
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._submit_recipe_serialize(
            recipe_submission_create=recipe_submission_create,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponseRecipeCreateResult",
            "422": "WrappedValidationError",
            "200": "StandardResponseRecipeCreateResult",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def submit_recipe_with_http_info(
        self,
        recipe_submission_create: RecipeSubmissionCreate,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseRecipeCreateResult]:
        """Submit community recipe

        Submit a community-contributed recipe for review. The recipe enters a pending state until reviewed and approved by an admin.

        :param recipe_submission_create: (required)
        :type recipe_submission_create: RecipeSubmissionCreate
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._submit_recipe_serialize(
            recipe_submission_create=recipe_submission_create,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponseRecipeCreateResult",
            "422": "WrappedValidationError",
            "200": "StandardResponseRecipeCreateResult",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def submit_recipe_without_preload_content(
        self,
        recipe_submission_create: RecipeSubmissionCreate,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Submit community recipe

        Submit a community-contributed recipe for review. The recipe enters a pending state until reviewed and approved by an admin.

        :param recipe_submission_create: (required)
        :type recipe_submission_create: RecipeSubmissionCreate
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._submit_recipe_serialize(
            recipe_submission_create=recipe_submission_create,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "201": "StandardResponseRecipeCreateResult",
            "422": "WrappedValidationError",
            "200": "StandardResponseRecipeCreateResult",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _submit_recipe_serialize(
        self,
        recipe_submission_create,
        x_api_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params["X-API-Key"] = x_api_key
        # process the form parameters
        # process the body parameter
        if recipe_submission_create is not None:
            _body_params = recipe_submission_create

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/v1/recipes/library/submit",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def track_recipe_share(
        self,
        recipe_id: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseRecipeCounterResult:
        """Increment recipe share count

        Increment the share counter for a recipe. Call this endpoint when a user shares the recipe externally.

        :param recipe_id: (required)
        :type recipe_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._track_recipe_share_serialize(
            recipe_id=recipe_id,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeCounterResult",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def track_recipe_share_with_http_info(
        self,
        recipe_id: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseRecipeCounterResult]:
        """Increment recipe share count

        Increment the share counter for a recipe. Call this endpoint when a user shares the recipe externally.

        :param recipe_id: (required)
        :type recipe_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._track_recipe_share_serialize(
            recipe_id=recipe_id,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeCounterResult",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def track_recipe_share_without_preload_content(
        self,
        recipe_id: StrictStr,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Increment recipe share count

        Increment the share counter for a recipe. Call this endpoint when a user shares the recipe externally.

        :param recipe_id: (required)
        :type recipe_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._track_recipe_share_serialize(
            recipe_id=recipe_id,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeCounterResult",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _track_recipe_share_serialize(
        self,
        recipe_id,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        if recipe_id is not None:
            _path_params["recipe_id"] = recipe_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/v1/recipes/library/{recipe_id}/share",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def track_recipe_use(
        self,
        recipe_id: StrictStr,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseRecipeCounterResult:
        """Increment recipe use count

        Increment the use counter for a recipe. Call this endpoint when an authenticated user activates or runs a recipe.

        :param recipe_id: (required)
        :type recipe_id: str
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._track_recipe_use_serialize(
            recipe_id=recipe_id,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeCounterResult",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def track_recipe_use_with_http_info(
        self,
        recipe_id: StrictStr,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseRecipeCounterResult]:
        """Increment recipe use count

        Increment the use counter for a recipe. Call this endpoint when an authenticated user activates or runs a recipe.

        :param recipe_id: (required)
        :type recipe_id: str
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._track_recipe_use_serialize(
            recipe_id=recipe_id,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeCounterResult",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def track_recipe_use_without_preload_content(
        self,
        recipe_id: StrictStr,
        x_api_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Increment recipe use count

        Increment the use counter for a recipe. Call this endpoint when an authenticated user activates or runs a recipe.

        :param recipe_id: (required)
        :type recipe_id: str
        :param x_api_key:
        :type x_api_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._track_recipe_use_serialize(
            recipe_id=recipe_id,
            x_api_key=x_api_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeCounterResult",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _track_recipe_use_serialize(
        self,
        recipe_id,
        x_api_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        if recipe_id is not None:
            _path_params["recipe_id"] = recipe_id
        # process the query parameters
        # process the header parameters
        if x_api_key is not None:
            _header_params["X-API-Key"] = x_api_key
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/v1/recipes/library/{recipe_id}/use",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def update_recipe(
        self,
        recipe_id: StrictStr,
        recipe_update: RecipeUpdate,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseRecipeDetailRead:
        """Update recipe

        Update an existing recipe in the library. Requires service credential authentication. Only provided fields are updated. The recipe is re-synced to the knowledge hub after the update.

        :param recipe_id: (required)
        :type recipe_id: str
        :param recipe_update: (required)
        :type recipe_update: RecipeUpdate
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._update_recipe_serialize(
            recipe_id=recipe_id,
            recipe_update=recipe_update,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDetailRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def update_recipe_with_http_info(
        self,
        recipe_id: StrictStr,
        recipe_update: RecipeUpdate,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseRecipeDetailRead]:
        """Update recipe

        Update an existing recipe in the library. Requires service credential authentication. Only provided fields are updated. The recipe is re-synced to the knowledge hub after the update.

        :param recipe_id: (required)
        :type recipe_id: str
        :param recipe_update: (required)
        :type recipe_update: RecipeUpdate
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._update_recipe_serialize(
            recipe_id=recipe_id,
            recipe_update=recipe_update,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDetailRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def update_recipe_without_preload_content(
        self,
        recipe_id: StrictStr,
        recipe_update: RecipeUpdate,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Update recipe

        Update an existing recipe in the library. Requires service credential authentication. Only provided fields are updated. The recipe is re-synced to the knowledge hub after the update.

        :param recipe_id: (required)
        :type recipe_id: str
        :param recipe_update: (required)
        :type recipe_update: RecipeUpdate
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._update_recipe_serialize(
            recipe_id=recipe_id,
            recipe_update=recipe_update,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseRecipeDetailRead",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _update_recipe_serialize(
        self,
        recipe_id,
        recipe_update,
        x_assistant_service_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        if recipe_id is not None:
            _path_params["recipe_id"] = recipe_id
        # process the query parameters
        # process the header parameters
        if x_assistant_service_key is not None:
            _header_params["X-Assistant-Service-Key"] = x_assistant_service_key
        # process the form parameters
        # process the body parameter
        if recipe_update is not None:
            _body_params = recipe_update

        return self.api_client.param_serialize(
            method="PATCH",
            resource_path="/api/v1/recipes/library/{recipe_id}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )
