# coding: utf-8

"""
Cobo Agentic Wallet Service

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from pydantic import validate_call, Field, StrictFloat, StrictStr
from typing import Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from cobo_agentic_wallet_api.models.execute_script_request import ExecuteScriptRequest
from cobo_agentic_wallet_api.models.standard_response_execute_script_response import (
    StandardResponseExecuteScriptResponse,
)
from cobo_agentic_wallet_api.models.standard_response_list_script_brief import (
    StandardResponseListScriptBrief,
)

from cobo_agentic_wallet_api.api_client_async import AsyncApiClient, RequestSerialized
from cobo_agentic_wallet_api.api_response import ApiResponse
from cobo_agentic_wallet_api.rest_async import AsyncRESTResponse


class AsyncScriptToolsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client: AsyncApiClient = None) -> None:
        if api_client is None:
            api_client = AsyncApiClient.get_default()
        self.api_client = api_client

    @validate_call
    async def execute_script(
        self,
        execute_script_request: ExecuteScriptRequest,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseExecuteScriptResponse:
        """Execute a script

        Look up a registered script by func_name and execute it with the given parameters. Returns the script output or an error message.

        :param execute_script_request: (required)
        :type execute_script_request: ExecuteScriptRequest
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._execute_script_serialize(
            execute_script_request=execute_script_request,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseExecuteScriptResponse",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def execute_script_with_http_info(
        self,
        execute_script_request: ExecuteScriptRequest,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseExecuteScriptResponse]:
        """Execute a script

        Look up a registered script by func_name and execute it with the given parameters. Returns the script output or an error message.

        :param execute_script_request: (required)
        :type execute_script_request: ExecuteScriptRequest
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._execute_script_serialize(
            execute_script_request=execute_script_request,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseExecuteScriptResponse",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def execute_script_without_preload_content(
        self,
        execute_script_request: ExecuteScriptRequest,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Execute a script

        Look up a registered script by func_name and execute it with the given parameters. Returns the script output or an error message.

        :param execute_script_request: (required)
        :type execute_script_request: ExecuteScriptRequest
        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._execute_script_serialize(
            execute_script_request=execute_script_request,
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseExecuteScriptResponse",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _execute_script_serialize(
        self,
        execute_script_request,
        x_assistant_service_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_assistant_service_key is not None:
            _header_params["X-Assistant-Service-Key"] = x_assistant_service_key
        # process the form parameters
        # process the body parameter
        if execute_script_request is not None:
            _body_params = execute_script_request

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/v1/script-tools/execute",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def list_scripts(
        self,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseListScriptBrief:
        """List registered scripts

        Return all in-memory registered scripts.

        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_scripts_serialize(
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListScriptBrief",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def list_scripts_with_http_info(
        self,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseListScriptBrief]:
        """List registered scripts

        Return all in-memory registered scripts.

        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_scripts_serialize(
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListScriptBrief",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def list_scripts_without_preload_content(
        self,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """List registered scripts

        Return all in-memory registered scripts.

        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._list_scripts_serialize(
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListScriptBrief",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _list_scripts_serialize(
        self,
        x_assistant_service_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_assistant_service_key is not None:
            _header_params["X-Assistant-Service-Key"] = x_assistant_service_key
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/api/v1/script-tools",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )

    @validate_call
    async def reload_all_scripts(
        self,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> StandardResponseListScriptBrief:
        """Reload all scripts

        Return all code-defined scripts. Aladdin calls this to discover available scripts and stores them in its own database.

        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._reload_all_scripts_serialize(
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListScriptBrief",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def reload_all_scripts_with_http_info(
        self,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> ApiResponse[StandardResponseListScriptBrief]:
        """Reload all scripts

        Return all code-defined scripts. Aladdin calls this to discover available scripts and stores them in its own database.

        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._reload_all_scripts_serialize(
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListScriptBrief",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def reload_all_scripts_without_preload_content(
        self,
        x_assistant_service_key: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]],
        ] = None,
    ) -> AsyncRESTResponse:
        """Reload all scripts

        Return all code-defined scripts. Aladdin calls this to discover available scripts and stores them in its own database.

        :param x_assistant_service_key:
        :type x_assistant_service_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._reload_all_scripts_serialize(
            x_assistant_service_key=x_assistant_service_key,
        )

        _response_types_map: Dict[str, Optional[str]] = {
            "200": "StandardResponseListScriptBrief",
            "422": "WrappedValidationError",
        }
        response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
        return response_data

    def _reload_all_scripts_serialize(
        self,
        x_assistant_service_key,
    ) -> RequestSerialized:
        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # set the HTTP header `Accept`
        _header_params = {"Accept": "application/json", "Content-Type": "application/json"}

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_assistant_service_key is not None:
            _header_params["X-Assistant-Service-Key"] = x_assistant_service_key
        # process the form parameters
        # process the body parameter

        return self.api_client.param_serialize(
            method="POST",
            resource_path="/api/v1/script-tools/reload",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
        )
